### ISSUE TITLE
[MEJ-001] 정적 팩토리 메서드의 정체성

### ISSUE THREAD

**Issue by ssh2957** [Glenn-syj/more-effective-java#10]
Based on: https://github.com/Glenn-syj/more-effective-java/pull/3 by clare-u

##### 들어가며

서현이의 글을 읽기전 저는 싱글톤패턴이 정적 팩토리 메서드중 한가지로 보았습니다. 

책에서도 "instance 혹은 getInstance "가 정적 팩토리 메서드의 한 종류라고 되어 있었기 때문입니다. 하지만 서현이의 글을 읽으니 싱글톤 디자인 패턴과 정적 팩토리 메서드는 다른 분류로 보고있다고 나와있습니다. 그래서 더 조사해본 결과 싱글톤 디자인은 정적 팩토리를 더 유용하게 사용하기 위해서 탄생했다고 합니다. 그렇기 때문에 정적팩토리의 단점을 극복하고 상속도 가능한것 입니다. 

그래서 서현이의 글을 통해 싱글톤과 정적 팩토리 메서드가 다른 것이라는것을 알수 있어서 좋았습니다. 하지만 궁금점도 생겼습니다.

이제 싱글톤과 정적 팩토리가 다른것은 이해 했는데 왜 책에서 "instance 혹은 getInstance "가 정적 팩토리 메서드라고 나와있는지 모르겠습니다. 제가 혹시나 해서 실험을 해보니 

매개변수 getInstance 함수를 제가 직접 만들지 않으면 애초에 메서드를 불어오지도 않고 

매개변수 이름도 a로 바꾸니 instance 매개변수로 불러오지 못했습니다. 

```java
public class Settings2 {
	private static final Settings2 a = new Settings2();

	// 싱글톤 인스턴스 생성
	private Settings2() {
	};



	public static void main(String[] args) {
		
		
		Settings2 set1 = Settings2.
		Settings2 set2 = Settings2.getInstance();

		
	}

}
```

정적팩토리메서드는 이미 자바 내부에 저장된 함수를 불러오는 것입니다.

하지만 getinstance() 의 경우 저희가 직접 만들어 줘야지만 사용할수 있는데 그렇다면 정적 팩토리 메서드의 개념은 자바 내부에 있는 함수+ 정적팩토리메서드의 개념을 활용한 우리가 만들어낸 함수들( getinstance() 등등) 을 다 포함하고 있는지

아니라면 자바 내부의 함수들만 정적 팩토리 메서드에 포함되는데 책에 잘못나온것인지 궁금합니다!

**Comment by clare-u** [comment]
제가 이해한 대로 한번 더 요약해 보겠습니다.

### 싱글턴 패턴이란?
싱글턴 패턴은 클래스의 객체가 하나만 생성되고, 어디서든지 접근할 수 있도록 하는 디자인 패턴입니다. 구현하는 방법 중 한 가지가 정적 팩토리 메서드를 사용하는 것입니다. 이 경우, 클래스 내부에 private static 인스턴스를 유지하고, 외부에서는 이 인스턴스에 접근할 수 있는 public static 메서드를 제공하게 될 것입니다.

### 정적 팩토리 메서드란?
정적 팩토리 메서드는 객체를 반환하는 정적 메서드입니다. 이 방법은 생성자를 통해 객체를 생성하는 대신, 클래스 내에 정의된 특정 메서드를 통해 객체에 접근하는 방법을 얻습니다. 이 메서드는 보통 getInstance, valueOf, newInstance 등의 이름으로 생성하며, 호출에 따라 새 객체를 생성하거나 기존 객체를 반환합니다.

### 제가 알기로는..
결론적으로 getInstance 메서드를 직접 생성하지 않으면 불러와지지 않는 상태가 맞습니다. getInstance 등 정적 팩터리 메소드는 자바 내부에 미리 정의되어 있지 않으므로 개발자가 필요에 따라 클래스 내에 명시적으로 정의해야 합니다. 따라서 책의 내용이 틀렸다기보단, 싱글턴 패턴으로 직접 생성한 getInstance 메서드는 정적 팩토리 메서드의 한 예로 볼 수 있습니다.

**Comment by clare-u** [comment]
> 제가 이해한 대로는 싱글턴 패턴을 구현하는 방법 중 한 가지가 정적 팩토리 메서드를 사용하는 것입니다.
> 
> ### 정적 팩토리 메서드란?
> 정적 팩토리 메서드는 객체를 반환하는 정적 메서드입니다. 생성자를 통해 객체를 생성하는 대신, 클래스 내에 정의된 특정 메서드를 통해 객체에 접근하는 방법을 얻습니다. 이 메서드는 직접 생성해서 사용해야 하며 보통 getInstance, valueOf, newInstance 등의 이름으로 생성하며, 호출에 따라 새 객체를 생성하거나 기존 객체를 반환합니다.
> 
> ### 제가 알기로는..
> 결론적으로 getInstance 메서드를 직접 생성하지 않으면 불러와지지 않는 상태가 맞습니다. getInstance 등 정적 팩터리 메소드는 자바 내부에 미리 정의되어 있지 않으므로 개발자가 필요에 따라 클래스 내에 명시적으로 정의해야 합니다. 따라서 책의 내용이 틀렸다기보단, 싱글턴 패턴으로 직접 생성한 getInstance 메서드는 정적 팩토리 메서드의 한 예로 볼 수 있습니다.

**Comment by ssh2957** [comment]
자세한 답변 감사합니다! 그럼  객체를 반환하는 정적 메서드 즉 생성자를 통하지 않고 메서드를 통해서 인스턴스를 만드는 행위 자체를 정적 메서드라고 한다 라고 이해하면 되는건가요?
