### ISSUE TITLE
[MEJ-005] 정적 · 비정적 멤버 클래스에 대한 질문

### ISSUE THREAD

**Issue by clare-u** [Glenn-syj/more-effective-java#107]
Based on: #101 by @ssh2957 

---
이번주에도 글 잘 보았습니다! 요약해주신 부분 중 static과 참조에 대해 더 고민해 보았는데요,
비정적 멤버 클래스는 바깥 클래스의 인스턴스와의 강한 참조 관계로 인해 비정적 멤버 클래스의 인스턴스가 존재하는 한, 바깥 클래스의 인스턴스는 가비지 컬렉터에 의해 수거될 수 없다고 이해했습니다. 
또한 이 이해가 맞다면, 반대로 정적 멤버 클래스의 인스턴스는 바깥 클래스의 인스턴스와 독립적으로 존재하므로, 바깥 클래스의 인스턴스가 가비지 컬렉션의 대상이 될 때 정적 멤버 클래스의 인스턴스에는 영향을 미치지 않는다고 생각했는데, 이 두가지 이해가 맞을까요?

**Comment by ssh2957** [comment]
넵 서현님이 이해하신 내용이 맞습니다. 비정적 멤버 클래스는 바깥 클래스의 인스턴스에 대한 강한 참조를 유지하기 때문에, 비정적 멤버 클래스의 인스턴스가 존재하는 한, 바깥 클래스의 인스턴스는 가비지 컬렉터에 의해 수거될 수 없습니다. 따라서 메모리 누수가 발생할수도 있습니다. 

반면에 정적 멤버 클래스는 바깥 클래스의 인스턴스와 독립적으로 존재하기 때문에, 바깥 클래스의 인스턴스가 가비지 컬렉션의 대상이 될 때 정적 멤버 클래스의 인스턴스에는 영향을 미치지 않습니다. 정적 멤버 클래스는 바깥 클래스의 인스턴스에 대한 참조를 갖지 않기 때문에, 이러한 독립성을 유지할 수 있습니다.
