### ISSUE TITLE
[MEJ-005] 프로그래밍의 거시적인 관점

### ISSUE THREAD

**Issue by ssh2957** [Glenn-syj/more-effective-java#108]
based on: #102 by @yngbao97
예진 님의 글을 읽고 코드를 실험해 보며 상수 인터페이스가 정확히 어떤 개념인지 알게 되었습니다.
그리고 왜 상수 인터페이스가 문제인지에 대한 4가지 이유를 알게 되었고 상수 인터페이스 문제점 4번을 보며 item 4를 공부할 때는 인스턴스화를 왜 막아야하는지 이해를 잘 못했었는데 이러한 4번 문제를 막기 위해서 유틸리티 클래스의 생성자를 private로 막아야 한다는걸 제대로 이해할수 있었습니다. 
또한 상수가 인터페이스에 저장되어 있으므로 바로 불러올 수 있어 정규화된 이름이 아닌 바로 상수로 불러올 수 있는 점이 저는 굉장히 편리하게 느껴졌는데
이러한 점이 오히려 이름공간을 오염시킨다는 점을 관점에서 보니 프로그래밍할 때는 당장의 편의성도 중요하지만, 거시적인 관점에서 프로그래밍의 중요성을 알게 되는 글이었습니다. 이번에도 이해하기 쉬운 예시를 통한 글 감사합니다.

**Comment by yngbao97** [comment]
개념을 이해하시는데에 도움이 되었다니 다행입니다!
저도 상수 인터페이스 개념을 처음 접해서 이런저런 코드로 단순하게 정리해보려고 노력했는데 뿌듯하네요.

앞으로도 각 아이템에서 전달하고자 하는 바를 조금 더 멀리서 바라보고 효과적으로 정리해볼 수 있도록 공부해보겠습니다.
감사합니다:)
