### ISSUE TITLE
[MEJ-001] 빌더 내부클래스 정의에 관한 예시 코드 요청

### ISSUE THREAD

**Issue by yngbao97** [Glenn-syj/more-effective-java#11]
Based on: #3 by clare-u

## 빌더 내부클래스 정의에 관한 예시 코드 요청

최근 Spring과 DB를 연결하는 연습을 했던 경험에 비추어, 설계과정에 객체 일관성을 고려하는 것이 얼마나 중요한지 이 글을 통해 더 이해할 수 있었어요. Builder 의 필요성에 대해 잘 정리해주셔서 감사합니다!

제가 아직 잘 모르지만, 책 내용으로 봤을 때 빌더가 Inner Class로 정의 되는 것 같은데 아직 익숙하지 않은 방식이라서요.
빌더 호출 코드만 적혀 있는 부분이 조금 어려운 것 같습니다.

빌더클래스를 정의하는 부분도 [3. 빌더 패턴] 에 함께 적어주신다면 예시코드에 있는 빌더 방식 객체 생성까지 흐름이 더 잘 이해될 것 같습니다!

**Comment by clare-u** [comment]
제일 중요한 부분을 예시를 들지 않고 글을 올려버렸었네요! 바로 제 #3 pr에 내용 추가하여 커밋했습니다.

아직 merge되지 않은 상태라, md 뷰어로 편히 보려면 [제 브랜치](https://github.com/clare-u/more-effective-java/blob/clare-u/chapter_02/item02_%EC%9C%A0%EC%84%9C%ED%98%84_%EB%B9%8C%EB%8D%94-%ED%8C%A8%ED%84%B4-%EC%97%B0%EC%8A%B5%ED%95%98%EA%B8%B0.md)로 와서 읽어주시면 될 것 같아 링크 달겠습니다.

좋은 질문 덕분에 글이 풍부해질 수 있었네요 감사합니다! 혹시 추가 질문 있다면 언제든지 또 comment 주시길 바랍니다.

**Comment by yngbao97** [comment]
>여기서 주목할 부분은 각 Setter 함수 마지막 반환 구문인 return this 부분이다. 여기서 this란 StudentBuilder 객체 자신을 말한다.
>즉, 빌더 객체 자신을 리턴함으로써 빌더 클래스의 메서드를 체이닝(Chaining) 형태로 호출함으로써 자연스럽게 인스턴스를 구성

추가해주신 빌더 클래스 예시 코드와 체이닝 형태가 이루어질 수 있는 이유에 대해 포인트를 잘 설명해주셔서 좋네요! 
답변 감사합니다! 고생하셨습니다👍
