### ISSUE TITLE
[MEJ-005] 역직렬화 과정과 readObject 메서드에 대한 보충 설명

### ISSUE THREAD

**Issue by Glenn-syj** [Glenn-syj/more-effective-java#110]
based on: #104 by @undeadtimo 

### 들어가며

해당 글에서 중점은 `readObject()`에 있지만, 구체적으로 서술되어 있지는 않아 자바 내에서의 역직렬화 과정에 대한 구체적인 설명을 드리려고 합니다. `readObject` 메서드가 역직렬화 과정 속에서 어떠한 역할을 갖고 있는지는, 전체적인 역직렬화 과정에 대한 이해 속에 있기 때문입니다.

### readObject 메소드란

[자바 명세](https://docs.oracle.com/en/java/javase/17/docs/specs/serialization/input.html)에 따르면,  `readObject` 메소드는 직렬화 가능한 객체들의 필드를 역직렬화를 관리합니다. 매개변수로는 아래와 같이 `ObjectInputStream` 타입이 들어갑니다.

```java
private void readObject(ObjectInputStream stream)
    throws IOException, ClassNotFoundException;
```

직렬화가 가능한 클래스 내에 작성된 `readObject()` 메서드는 `ObjectInputStream` 내부에서 이용하게 됩니다. 그렇다면 `readObject` 메서드는 왜 역직렬화 과정에서 이용될까요?

### 자바에서의 역직렬화 과정

1. 콘텐츠 스트리밍

직렬화된 인스턴스의 스트림 속에는 클래스의 메타데이터, 필드의 타입 정보나 값들이 들어있습니다. 역직렬화 시에는 JVM이 바이트 스트림에서 메타데이터를 읽어옵니다. 만약 인스턴스의 클래스에 대한 바이트코드가 JVM에 올라와있지 않다면 `ClassNotFoundException`을 반환합니다.

2. 생성자 없는 초기화

앞서 스트리밍 과정에서, JVM이 읽어온 메타데이터에서 `Serializable`혹은 `Externalizable` 인터페이스가 구현되어 있어야만 객체가 초기화될 수 있습니다. 역직렬화 과정에서의 바이트코드를 설명하는 [howtodoingjava.com](https://howtodoinjava.com/java/serialization/how-deserialization-process-happen-in-java/)의 글이 있어, 주로 번역에 가까운 참고를 했습니다. 

```java
public class SimpleProgram
{
    public static void main(String[] args)
    {
        System.out.println("Hello World!");
    }
}
```

```bytecode
public class SimpleProgram extends java.lang.Object{
public SimpleProgram();
  Code:
   0:	aload_0
   1:	invokespecial	#1; //Method java/lang/Object."":()V
   4:	return

public static void main(java.lang.String[]);
  Code:
   0:	getstatic	#2; //Field java/lang/System.out:Ljava/io/PrintStream;
   3:	ldc	#3; //String Hello World!
   5:	invokevirtual	#4; //Method java/io/PrintStream.println:(Ljava/lang/String;)V
   8:	return
}
```

1번 코드에서는 해당 인스턴스 최상위 클래스의 생성자를 호출합니다. 역직렬화 과정에서는 인스턴스의 상위 클래스가 `Serializable`을 구현해야 하고, 상위 클래스 계층에서 구현되어 있지 않다면 기본 생성자를 가지고 있어야 합니다. 물론, 이 과정에서 클래스의 `SerialVersionUID`가 일치하는지 역시 검증됩니다.

3. 초기화 이후

2번에서 상위 클래스 중 하나의 기본 생성자를 통해 인스턴스가 생성되었습니다. 이 이후에는 생성자가 이용될 일이 없습니다.

이제는 JVM이 바이트 스트림을 읽어온 인스턴스의 메타데이터를 이용해 2번에서 생성된 인스턴스에 타입 정보를 설정합니다. JVM은 정적 필드를 설정한 뒤에 `readObject()` 메서드를 호출합니다. 만약 `readObject` 메서드가 재정의되어있다면, 해당 클래스의 `readObject` 메서드가 이용됩니다. 

### References

https://docs.oracle.com/en/java/javase/17/docs/specs/serialization/input.html

https://howtodoinjava.com/java/serialization/how-deserialization-process-happen-in-java/

**Comment by undeadtimo** [comment]
readObject 메서드에 대한 보충설명을 해주셔서 감사합니다. Glenn-syj님의 글을 읽고 해당 메서드에 대한 이해를 더 깊이있게 할 수 있었습니다.

직렬화 과정에서 클래스의 필드에 대한 정보가 저장되고 이러한 메타데이터가 존재하지 않다면 readObject 메서드를 통한 역직렬화 과정에서 에러가 발생하게 되는 것이군요.

또한, 제가 작성한 글과 관련하여, 역직렬화를 하고자 하는 클래스의 상위 클래스를 호출하게 되며, 상위 클래스가 Serializable을 구현하고 있는지, 기본 생성자를 갖고 있는지, SerialVersionUID가 일치하는지를 보고 있다는 것을 알게 되었습니다.

따라서, 역직렬화를 통해 인스턴스의 타입 정보와 정적 필드가 설정된 이후에 readObject 메서드가 호출이 되는 것인데,

역직렬화를 위한 readObject가 재정의 되어있다면, 재정의된 readObject 메서드가 호출될 것이지만, 필드 값을 참조하는 형태로 재정의 하게 된다면 오류가 발생하는 것이 되겠군요.

구체적인 예시를 첨부한 보충설명에 다시 감사드립니다.
