### ISSUE TITLE
[MEJ-005] 다중 상속의 문제점과 다중 구현으로의 보완

### ISSUE THREAD

**Issue by yngbao97** [Glenn-syj/more-effective-java#111]
Based on: #103 by @clare-u 
<hr>

자바에서 다중 상속을 왜 허용하지 않는지에 대해서 깊게 고민하지 않았었는데, 작성해주신 탐구글을 통해 인터페이스와 상속의 차이점에 대해 다시 한번 생각해볼 수 있었습니다.
글로만 읽으면 헷갈릴 수 있는 내용인데 직관적인 예시 코드를 첨부해주셔서 혼란없이 쉽게 이해가 됐어요!

다중 상속을 허용하지 않는 이유에 대해 '다이아몬드 문제'라는 개념을 소개하며, 자바에서는 어떤 방법을 통해 이 문제를 보완하며 기능을 제공하고 있는지까지 탐구해주셔서 매우 유익했습니다.
상속도 구현도 앞으로 자주 사용하게 될텐데, 탄탄한 기초개념을 다지는데 도움이 될 것 같습니다!

늘 새로운 개념을 유익하게 정리해주셔서 배울 점이 많아 좋았는데, 마지막 글이라니 많이 아쉬워요
서현님이 잘해주셨던 것처럼 저희도 유익한 탐구내용을 공유하도록 계속해서 노력할테니 종종 와서 읽어보시고 궁금한 부분이 있다면 따로 말씀도 해주세요 ㅎㅎ  
이번 탐구도 고생하셨습니다! 감사합니다!

**Comment by clare-u** [comment]
저도 다중 상속 문제에 대해 탐색하며 바로 다이아몬드 문제에 대한 글들을 보고 유익하고 흥미롭다고 느꼈었는데, 같은 감정을 공유했다니 기쁩니다!! 따뜻한 말씀 감사드려요. 저도 이번 주차가 마무리 주차라고 생각하니 많이 아쉽지만, 기초를 더 다지도록 마음 강하게 먹고 떠나도록 하겠습니다..! 물론 매주 공유되는 item의 요약과 심화 탐구, 논의들을 보러 자주 찾아올 예정입니다 ㅎㅎ 앞으로도 좋은 글 잘 부탁드리겠습니다
