### ISSUE TITLE
[MEJ-001] 하위타입객체의 멤버변수와 멤버메서드 호출 결과에 대한 질문

### ISSUE THREAD

**Issue by yngbao97** [Glenn-syj/more-effective-java#12]
Based on: #2 by FickleBoBo

## 하위타입객체의 멤버변수와 멤버메서드 호출 결과에 대한 질문

정적 팩터리 메서드가 다른 타입의 인스턴스를 반환하는 결과에 대해 직접 실험해본 부분이 인상깊고, 다양한 형태로 실험해주셔서 이해가 잘 됐습니다. 다형성의 활용에 대해서도 다시 한번 생각해볼 수 있었습니다.

다만, Case3에서 멤벼 변수인 str을 호출하면 "car"가 출력되고 메서드인 whatIsThis()를 호출하면 "benz"가 출력되는 것이 상속관계 관련 글을 찾아봐도 잘 와닿지 않네요..

어떠한 차이로 나타나는 현상인지 이해하신 바가 있을까요?

**Comment by FickleBoBo** [comment]
```java
Car carTest1 = Car.getInstance(1);
System.out.println(System.identityHashCode(carTest1));    // 495053715
System.out.println(carTest1.str);                                          // car
carTest1.whatIsThis();                                                          // benz

Benz test1 = (Benz) carTest1;
System.out.println(System.identityHashCode(test1));        // 495053715
System.out.println(test1.str);                                              // benz
test1.whatIsThis();                                                              // benz

Car test2 = (Car) test1;
System.out.println(System.identityHashCode(test2));        // 495053715
System.out.println(test2.str);                                              // car
test2.whatIsThis();                                                              // benz

Car carTest2 = Car.getInstance(2);
System.out.println(System.identityHashCode(carTest2));        // 1922154895
System.out.println(carTest2.str);                                              // car
carTest2.whatIsThis();                                                              // car
```

※ 오개념 주의 ※

출력 결과를 통해 멤버 변수(필드)의 경우 현재 선언 타입에 따라 출력이 되며 메서드의 경우 오버라이딩된 가장 밑바닥? 값이 나오는 것을 볼 수 있었습니다. 
이러한 현상에 대해 찾아보며 자바 메모리 구조와 동적 바인딩에 대한 이해가 필요한 것 같았습니다. 양질의 자료를 찾기 어려워 제가 이해한 바로 해석하자면 다형성을 적용해 부모 타입으로 선언한 경우 멤버 변수와 멤버 메서드 모두 부모 타입으로 컴파일 되지만 멤버 메서드는 런타임 단계에서 호출될 때 동적 바인딩으로 자식 타입으로 오버라이딩된 메서드를 호출하기 때문인 것으로 이해했습니다.(컴파일 단계의 메서드랑 다른 애임)

꼭 다시 찾아보십시오

**Comment by yngbao97** [comment]
컴파일 단계의 메서드와 런타임 단계의 인스턴스 생성과 멤버 메서드 사용에 대해 조사해봐야겠네요!
공부해볼 수 있는 포인트를 잘 답변해주셔서 감사합니다~ 고생하셨습니다!
