### ISSUE TITLE
[MEJ-001] 구체적인 예시를 통한 이해

### ISSUE THREAD

**Issue by ssh2957** [Glenn-syj/more-effective-java#13]
Based on: #1 by yngbao97

### 구체적인 예시를 통한 이해

정적 팩토리 메서드라는 이름에 속아 정적 팩토리 메서드라는 내부 함수를 활용해서 인스턴스를 만드는것이 정적 팩토리 메서드라고 이해하고 있었는데  "객체 생성 없이 접근할 수 있는 static(정적) 키워드를 사용하여"  이부분을 통해 정적 메서드란 클래스 내부에서 static 을 활용하여 인스턴스를 만들어 이미 생성된 인스턴스를 활용할수 있게 하는것이라는 깨달음을 얻었습니다. 정적 키워드가 아닌 static(정적)으로 표현 해주셔서 좋았습니다. 

또한 회원카드를 만드는 코드에서 of 메서드를 통해 자신의 점수에 맞는 알파벳을 부여받고 Grade 함수를 통해 알파벳에 맞는 카드가 부여 받는 구체적인 과정을 통해 " 다양한 함수들을 활용하여 객체가 정보를 부여하는 과정을 볼 수있어서 좋았습니다. 

마지막으로 확실한 이해를 위해 질문이 있습니다. "static(정적) 키워드를 사용하여"  해당 클래스의 인스턴스를 반환하는 것이 정적 팩토리 메서드라고 나와있는데 이것이 static 을 활용하여 미리 인스턴스를 만들어서 할당해주는 방식과 함수에 static을 써서 할당해 주는 방식 이 두가지 case처럼  인스턴스가 static으로 정의되어 진다면 모두 정적팩토리 메서드의 개념안에 들어가는지 궁금합니다.

**Comment by yngbao97** [comment]
## 회원카드 예시 코드 관련 부가 설명

우선, Grade는 함수가 아니고 각 등급 클래스가 필수로 갖추어야 할 변수나 메서드를 규정한 '인터페이스'입니다. 
그리고, A, B, C...는 Grade인터페이스를 구현한 '클래스'입니다.
giveLevel 클래스는 매개변수에 따라 Grade인터페이스의 구현객체(등급 클래스)를 반환하는 of라는 이름의 정적 팩터리 메서드를 가지고 있는 것입니다.

따라서, 다양한 함수를 활용하여 객체가 정보를 부여하는 과정이라기보단 -> 하나의 정적 팩터리 메서드를 통해 다양한 형태의 인스턴스를 반환하는 것이라고 설명해야 합니다.

### 예시 코드 정정
사용했던 코드를 확인하며 답변을 하다보니, 제 예시가 정적 팩터리 메서드를 설명하기에 적절하지 않았던 것 같네요ㅠ
of 메서드를 giveLevel클래스가 아니라 Grade 인터페이스가 가지고 있어야 할 것 같습니다.
```
interface Grade {

    public static Grade of(int score) {
        if (score >= 90) {
            return new A();
        } else if (score >= 80) {
            return new B();
        } else if (score >= 70) {
            return new C();
        } else if (score >= 60) {
            return new D();
        } else {
            return new F();
        }
    }

    String toText();
}
```
*Java 8부터 인터페이스에 static 메소드 선언 가능

## 필드에 미리 생성된 인스턴스를 반환하는 것과, 메서드를 통해 인스턴스를 생성하여 반환하는 방식의 차이

먼저, 하나의 인스턴스를 재활용하고자 한다면 static 키워드를 사용해야 하고 static변수를 반환하려는 메서드는 반드시 static키워드를 가지고 있어야 해당 변수에 접근할 수 있습니다. 

정적 팩터리 메서드는 질문 주신 두 가지 case모두 정적 팩터리 메서드라고 볼 수 있지만, 차이점은 생성되는 객체 생성 시점이라고 생각합니다. 

해당 클래스와 각 정적 팩터리 메서드의 성격에 따라 구현하는 방식이 달라질 터라 차이점에 대해 다양한 예시와 정확한 답변을 드리기 어려울 것 같습니다.

static키워드 관련 간단한 강의 영상 공유드립니다. oracle 공식문서를 참고해보시는 것도 좋을 것 같네요!
위 설명 중 이해가 되지 않는 부분이 있다면 컨텍바랍니다,,

- [static키워드 영상](https://opentutorials.org/course/4074/27016)
- [oracle 공식문서]https://docs.oracle.com/javase/tutorial/java/javaOO/classvars.html
