### ISSUE TITLE
[MEJ-006] SuppressWarning 애노테이션 실제 사용에 대한 이해

### ISSUE THREAD

**Issue by yngbao97** [glenn-syj/more-effective-java#131]
Based on: #127 by @undeadtimo 
<hr>

알고리즘 풀이를 위해 배열 선언에서 List 로타입을 사용하는 경우 경고줄을 눌러 SuppressWarnings 애너테이션이 자동생성되어도 무슨 뜻이지 몰라 다시 삭제하고 경고줄이 뜬채로 사용하곤 했었는데요,

이번 아이템을 읽으며 실제 프로그램에서 경고줄을 어떻게 다뤄야 할지 배울 수 있었고, 이러한 기초개념을 창용님이 잘 정리해주셔서 책만 읽었을 때보다 더 쉽게 이해할 수 있었습니다.
같은 경고에 대한 중복 억제, 존재하지 않는 경고에 대한 억제에 대해서도 다뤄주셔서 좋았습니다! 덕분에 앞으로는 경고줄을 발견했을 때 모른다고 무시하지 않고, 한번 더 읽어보고 애너테이션을 적극적으로 사용해볼 수 있을 것 같네요.
감사합니다!

**Comment by undeadtimo** [comment]
yngbao97님이 코드를 작성하면서 경고줄을 자세히보고 애너테이션을 적극적으로 사용하도록 도움을 드린 것 같아 뿌듯하네요!
