### ISSUE TITLE
[MEJ-001] 하위 타입 반환과 다형성에 대한 고민

### ISSUE THREAD

**Issue by FickleBoBo** [Glenn-syj/more-effective-java#15]
정적 팩터리 메서드의 장단점에 대한 각각의 설명을 예제를 통해 설명하며 이해를 도운 점이 좋았습니다. API를 만들 때, 구현 클래스를 공개하지 않고도, 그 객체를 반환할 수 있어, API를 작게 유지할 수 있다는 점이 다소 모호하게 느껴졌는데 interface HelloWorld 예제를 통해 개발자가 인터페이스만 이해하면 그 구현 클래스는 잘 구현됐을 것이라는 믿음?을 갖고 개발을 하면 되어 피로도를 낮출 수 있을 것이라는 생각이 들었습니다. 

이러한 특징은 반환 타입(인터페이스)의 하위 타입(구현 클래스)를 반환할 수 있기에 가능한 점이라고 생각하는데, 아직 하위 타입 반환에 대해 이해가 부족한 시점에 도움이 되었습니다. 

예시 코드를 보며 하위 타입의 객체를 반환할 수 있는 이유로 하위 타입은 상위 타입으로 다형성을 적용할 수 있어서, 자기 자신 타입을 반환하는 것과 동일하게 볼 수 있기 때문인가라고 생각해보았는데, 창용님은 어떻게 생각하시는지 궁금합니다.

**Comment by undeadtimo** [comment]
저도 FickleBoBo 님과 동일하게 생각합니다!
제가 작성한 글에서 보여드린 예시 코드는, 비록 올바른 형태의 정적 팩토리 메서드를 보여드린 것은 아니지만,

해당 예시 코드의 HelloMyself 메서드와 HelloRealFriend는 다형성 특성이 있기에, 상위 타입인 HelloWorld 클래스로 형변환되어 반환될 수 있습니다.

이러한 과정이 존재하기에, 클라이언트는 HelloMyself와 HelloRealFried 같은 구현 클래스들을 알지 않아도 되어, 상대적으로 작은 크기의 API 를 사용하기에 개발의 피로도가 줄어들게 됩니다..
