### ISSUE TITLE
[MEJ-001] 정적 팩토리 메소드 보다 생성자가 더 효율적인 상황에 대한 궁금증

### ISSUE THREAD

**Issue by undeadtimo** [Glenn-syj/more-effective-java#19]
Based on: #7 by @ssh2957 

---

 처음 떠오른 궁금증에서 출발하여, 직접 코드를 작성하고 그 결과를 비교하는 과정이, 자연스럽게 연결되고 구체적이어서 이해하기 좋았습니다.

 특히, 정적 팩토리 메소드와 싱글턴 패턴 디자인에 대해서, 
 '정적 팩토리 메소드 안에 싱글톤이 들어가는 것은 맞으나 모든 정적 팩토리 메서드가 싱글톤의 특징을 가지는 것은 아니다' 라고 정리해주어 이 둘의 관계를 더욱 잘 이해할 수 있었습니다.

 그러나 하나 궁금한 부분이 존재합니다. 결론에서 요일이 월, 화, 수 밖에 없다면 생성자를 이용하여 객체를 생성하는 것이 더 효율적이라고 하셨는데 이것은 코드의 길이 측면에서 말씀하신 것인지 궁금합니다.

 필요한 요일이 단지 월, 화, 수일 뿐이라고 하더라도, 인스턴스의 갯수를 제한하고, 메서드명을 통하여 의미를 전달할 수 있기 때문에,
 관리 및 테스트를 하게 되면 정적 팩토리 메소드를 사용하는 것이 장기적으로 더 효율적일 수 있다는 개인적인 생각이 들었기 때문입니다.

**Comment by ssh2957** [comment]
정적팩토리 메서드는 필요한 요일(월,화,수,목,금,토,일) 인스턴스를 미리 생산하기 때문에 만약 사용자가 필요한 요일이(월,화,수) 밖에 없다면 미리 생산한 (수~일) 까지가 필요 없으니 요일이 필요할때 마다 생산하는게 좋지 않을까? 생각했지만 창용님의 말대로 월,화,수 만 필요할 경우라도   월,화,수가 1번이 아닌 n번 이상 호출될 경우 정적 팩토리 메서드를 사용하는게 장기적으로 효율적이라는 말에 동의 하게 되었습니다. 덕분에 한번도 생각하여 제 의문점도 풀리도 정적 팩토리에 대한 이해도도 올라갔습니다 좋은 질문 감사합니다. 답변을 쓰면서 생각한건데 저희가 db에서 부서 테이블과 직원 테이블을 레프트 조인할시 만약 부서테이블에 아무도 사용하지 않는 부서가 있다고 하더라도(조인시 사원정보는 null로 표시될것이다) 직원 테이블에 직접 INSERT해서 부서정보를 넣어주는것 보다 부서테이블과 JOIN해서 넣어주는게 더 효율적인걸 볼수 있습니다. 정적 팩토리 메서드도 비슷한 맥락이라고 생각합니다.

**Comment by Glenn-syj** [comment]
> 답변을 쓰면서 생각한건데 저희가 db에서 부서 테이블과 직원 테이블을 레프트 조인할시 만약 부서테이블에 아무도 사용하지 않는 부서가 있다고 하더라도(조인시 사원정보는 null로 표시될것이다) 직원 테이블에 직접 INSERT해서 부서정보를 넣어주는것 보다 부서테이블과 JOIN해서 넣어주는게 더 효율적인걸 볼수 있습니다.

제가 직관적으로 이해하지 못해서 그러는데, 혹시 풀어서 설명해주실 수 있나요? 어떤 점에서 정적 팩토리 메소드와 관련있는지 궁금합니다!

**Comment by ssh2957** [comment]
@Glenn-syj 
정적 팩토리의 다른 특징 말고 창용님의 장기적인 효율이라는 말에만 집중해서 생각해 보았는데
직원정보가 있는 emp 테이블과 부서 정보가 있는 dep 테이블있습니다.
만약 회사에 있는 부서가 1. 회계 2. 마케팅 3. 인사 팀 3개가 있다고 했을때
실제로 우리가 가지고 있는 직원 정보에는 회계 마케팅 팀만 존재 한다면 마지막 인사팀 이라는 정보는 필요없을것 입니다. 
하지만 인사팀의 테이블이 있으므로 언제든지 인사팀의 직원 정보가 들어왔을때 인사팀의 정보를 매칭 시킬수 있는것 처럼
정적팩토리 메서드에서도 현재는 쓰이지 않는 다른 요일의 인스턴스를 미리 만들어서 쓰이지 않던 요일이 호출 되었을때 바로 
매칭 되는것을 유사하다고 보았습니다!

**Comment by Glenn-syj** [comment]
아하 그런 의미에서였군요! 자세히 풀어서 설명해주셔서 감사합니다!

**Comment by clare-u** [comment]
오 저도 잘 이해하지 못했었는데 풀어서 설명해주신 걸 들으니 DB도 더 잘 이해가 가네요!
