### ISSUE TITLE
[MEJ-001] 정적 팩토리 메소드 이해에서의 오개념 정정

### ISSUE THREAD

**Issue by Glenn-syj** [Glenn-syj/more-effective-java#21]
Based on: #4 by @undeadtimo 

### 들어가며

전반적으로 item01에 대한 이해도를 잘 보여주는 글인데요. 내용 이해가 잘못된 부분이 있어 보충적으로 작성합니다.

**코드 수정**

```java
public class HelloWorld {

    static HelloWorld friend(String name){
        if(name.equals("송창용")){
            return new HelloMyself();
        } else {
            return new HelloRealFriend();
        }
    }
}
```

위 코드는 인터페이스의 적절한 이용이라고 볼 수 없습니다. 오히려 클래스와 비슷하다고 볼 수 있겠네요. 인터페이스를 이용하고, Impl 클래스를 따로 만들었던 기억을 떠올려 보시면 편할 겁니다. 또한, 정적 팩터리 메서드를 잘못 이해하고 있는 코드이기도 합니다.

1. 구현 클래스의 공개

"구현 클래스를 공개하지 않는다"는 말은 "완전하게 구현된 메서드"를 보여주지 않는다는 말과 다릅니다. 만약 정적 팩토리 메서드가 위와 같다면, 기본 생성자 방식은 "완전하게 구현된 메서드"를 보이나요 보이지 않나요?

이러한 오해가 발생하는 이유는 상속/구현 관계를 놓치고 있기 때문입니다. 해당 구절에서 '구현 클래스'라는 말은 추상 클래스를 상속하거나 인터페이스를 구현하는 하위 클래스를 염두에 둡니다.

직관적이지는 않지만, 올려주신 코드를 기반으로 설명해보겠습니다. `HelloMySelf`와 `HelloRealFriend`는 아마도 `HelloWorld` 클래스를 상속받는 하위 클래스일 겁니다. 이러한 하위 클래스 객체를 반환했을 때, 반환값의 타입은 무엇이 될까요?

바로 상위 클래스인 `HelloWorld`입니다. 여기에서 `HelloMyself()`와 `HelloRealFriend()`를 통해 생성된 객체는 반환 과정에서 상위 클래스인 `HelloWorld`로 형 변환 됩니다. 따라서 클라이언트는 `HelloMyself`나 `HelloRealFriend`와 같은 구현 클래스를 알 수 없습니다.

2.  정적 팩토리 메소드 작성 시점과 반환 타입 클래스 존재

해당 파트에 대한 이해는 반쯤 맞습니다. 가장 잘못된 이유는 0번에서의 코드가 타당하지 않기 때문입니다. 이 파트에 대한 설명은 우리가 JDBC를 이용하기 위해 드라이버를 불러오던 방식을 생각하면 편합니다.

`Class.forName()`을 통해서 아직 스태틱 메모리에 로드되지 않았던 JDBC의 드라이버를 로드했었는데요. 컴파일 시점에서는 해당 메서드를 이용하는 부분에 대해 오류가 없기에 클래스가 없어도 상관없지만, 런타임 시점에는 인자로 들어간 클래스가 없다면 오류가 발생합니다.

```java
// https://stackoverflow.com/questions/53240626/what-does-static-factories-returned-object-need-not-exist-mean
public static MyInterface getMyInterfaceInstance() {
    return (MyInterface) Class.forName(System.getProperty("my.interface.implementation.class")).newInstance();
}
```

결국, 이 구절에서 말하고자 하는 코드는 위와 같습니다. 실제로 0번의 코드를 돌려보면 이미 컴파일 시점에서 존재하지 않는 클래스의 생성자를 이용하기에 오류가 뜹니다. 다음부터는 직접 한 번은 돌려보셔도 좋겠습니다. 그리고 왜 생성이 아니라 '로드'(load)라는 표현을 쓰는지도 다시 한 번 고려하면 더욱 잘 이해하실 수 있을 겁니다!

### Reference
https://stackoverflow.com/questions/53240626/what-does-static-factories-returned-object-need-not-exist-mean
https://stackoverflow.com/questions/8053095/what-is-the-actual-use-of-class-fornameoracle-jdbc-driver-oracledriver-while

**Comment by undeadtimo** [comment]
잘못된 이해를 바로잡아주셔서 감사합니다.

Glenn-syj님의 설명으로 반환된 하위 클래스의 형변환과 '구현 클래스의 공개' 에 대한 의미를 알게 되었습니다.

또한 '작성 시점과 반환타입의 존재'를 컴파일 시점과 런타임 시전으로 구분할 수 있게 되었습니다.
