### ISSUE TITLE
[MEJ-001] 메소드 시그니처, 패키지-프라이빗 내용을 읽고

### ISSUE THREAD

**Issue by clare-u** [Glenn-syj/more-effective-java#22]
Based on: #4 by @undeadtimo

---

> 메소드 시그니처란, 복잡하지 않은 개념으로 메소드의 매개변수 리스트 일컫는 말이다.

추가적으로 구글링 해 보니, 메소드 시그니처는 자바에서 프로그래머가 디자인한 메서드 구조를 의미하며 사실 **메소드 이름**과 매개변수 리스트로 구성된다고 합니다. 

같은 이름으로 선언된 메소드를 중복해서 정의한다는 것이 메소드 오버로딩이 맞지만, 메소드 시그니처는 메소드명까지 포함하는 개념이라고 이해하는 게 맞을 것 같네요!

참고 자료: [Method Signature in Java](https://www.scaler.com/topics/method-signature-in-java/)

---
> 책에서 설명하는 패키지-프라이빗은 4가지 접근 수준 단계 중 default 를 가리키는 것이다.

패키지 프라이빗에 대한 내용을 놓치고 있었는데, 덕분에 확실히 정의할 수 있어 다행입니다. 막연하게 패키지-프라이빗이면 `private` 접근 제한자를 의미한다고 생각했었는데, 현업 개발자 친구에게 질문해보니 공식 문서에서는 사용하지 않는 단어라서 지금까지 못 들어보았을 수 있다고 코멘트 해 주더라고요.

**Comment by undeadtimo** [comment]
추가적인 설명 감사합니다.

메서드 시그니처는 단지 매개변수의 타입과 리스트를 일컫는 말인 것으로 알았는데, 구체적으로는 '메소드 이름'까지 포함한 개념이었군요.

또한 패키지-프라이빗은 default 접근제한과 같은 의미의 단어인데 어째서 생소한 개념인지 의아했었는데, 공식문서에서 사용하지 않는 단어였기 때문이었네요.
