### ISSUE TITLE
[MEJ-002] 정적 팩터리의 메소드 참조를 공급자로 사용하는 부분에 대한 질문

### ISSUE THREAD

**Issue by clare-u** [Glenn-syj/more-effective-java#36]
Based on: #35 by @undeadtimo 

---

> 정적 팩터리의 메서드 참조를 공급자로 사용할 수 있다.
> 공급자란 인자를 받지 않고 제네릭 타입의 객체를 반환하는 함수형 인터페이스이다.
> 
> 함수형 인터페이스는 한 개의 추상 메서드를 가지고 있는 인터페이스를 말한다.
> 공급자를 사용하면 공급자를 통해 반환할 값이 필요할 때까지 연산을 지연시킬 수 있다는 장점이 있다.
> 
> 공급자를 사용하여 연산을 지연시켜야 하는 대표적인 예로는, 시간측정이 있다.
> 
> 나이를 계산한다고 할 때, 객체가 생성된 이후에 시간이 흘러서 나이가 증가할 수도 있다.
> 이 때, 현재 시점을 기준으로 나이를 측정하는 메서드를 바로 실행하지 않다가,
> 현재 나이를 출력해야 할 때 실행하도록 하는 것이다.

부분에서 질문이 있습니다! 공급자라는 개념도 낯설고, 함수형 인터페이스라는 개념도 낯설어서 혹시 부연설명 또는 코드 예시 추가를 해 주실 수 있을까요?

꼭 시간측정 예시가 아니어도 좋으니 추가 설명이 있으면 더 이해에 도움이 될 것 같습니다. 

예를 들어, 공급자를 통해 반환할 값이 필요할 때까지 연산을 지연시킨다는 부분 등도 잘 연상되지 않아 저에겐 이해하기 어려운 부분으로 느껴지네요.

**Comment by undeadtimo** [comment]
우선 개념의 구체적인 설명이 부족하여 이해를 어렵게 한 점 사과드립니다.

먼저 '함수형 인터페이스'에 대해 설명을 드리고, 이후 '공급자'와 '지연 연산'에 대해 알려드리겠습니다.

함수형 인터페이스란 JAVA 8부터 도입된 개념입니다.
함수형 인터페이스는 '하나의 추상 메서드'만을 갖는 인터페이스로, 해당 인터페이스를 구현한 클래스는 하나의 함수처럼 사용이 됩니다.

'공급자'란 마찬가지로 JAVA 8부터 도입된 개념으로, 함수형 인터페이스의 일종입니다.
공급자는 람다식을 이용해 지연호출할 구문을 지정하여, 호출하고자 할 시점에 get() 메서드를 통해 호출할 수 있도록 하는 인터페이스입니다.

공급자는 다른 클래스에 구현하여 해당 클래스를 하나의 함수처럼 사용할 수도 있고, 직접 변수의 타입형태로 사용하여 공급자를 구현할 수도 있습니다.

아래 예시를 보면, 람다식을 통해, getObject 메서드를 지연호출하는 것을 일반적인 즉시호출과 비교하여 보여주고 있습니다.

```java
// supplier를 사용하기 위한 import문.
import java.util.function.Supplier;

// supplier를 통해 지연 호출을 보여줄 CustomObject 클래스
class CustomObject {

    CustomObject (String value) {
        System.out.println(value);
    }
    
    // 이 메서드를 통해 '즉시' 또는 '지연' 호출하여 텍스트를 출력한다.
    public static CustomObject getObject(String value) {
        return new CustomObject(value);
    }
}

public class test {

    public static void main(String[] args) {
    	// Java 8부터 추가된 Supplier interface는 Lambda 형식을 통해 사용할 수 있다.
    	// '() -> ' 부분을 통해 메서드 호출 or 변수 생성, 초기화의 지연이 가능하다.
        Supplier<CustomObject> customObjectSupplier = () -> CustomObject.getObject("Lazy initialization");
        
        // 즉시 호출을 위해 CustomObject의 static 메서드 getObject를 호출하였다.
        CustomObject customObject = CustomObject.getObject("Eager initialisation");
        System.out.println("Supplier not called yet");
        
        // supplier 인터페이스의 메서드 get()을 호출하면, 람다 함수로 지정했던 구문이 실행된다.
        customObjectSupplier.get();

    }
}
```

위에서 설명한 나이를 측정하는 예시는, 지연 호출을 통해 실제 현실 시간을 기준으로 나이를 측정할 수 있도록 할 수 있음을 설명한 것이었습니다.

본문에서 나오는 Supplier<Elvis>는 Elvis 클래스의 인스턴스 생성을 원하는 시점에 불러오도록 지연호출 할 수 있다는 장점을 말하는 것입니다.

**Comment by clare-u** [comment]
덕분에 공급자와 함수형 인터페이스에 대해 알아갑니다. 코드는 물론 상세한 설명까지 감사드립니다. 지연 호출이 추가되면 실제 현실 시간까지 따라갈 수 있다는 점이 흥미롭네요! 람다식에 익숙하지 않은데 추가적으로 공부해 보아야겠습니다.
