### ISSUE TITLE
[MEJ-002] 메서드 인라이닝에 대한 질문

### ISSUE THREAD

**Issue by clare-u** [Glenn-syj/more-effective-java#37]
Based on: #32  by @FickleBoBo 

---

> transient나 volatile과 같은 제어자(modifier)의 사용을 고려해보거나, 메서드 인라이닝을 위해 final 메서드를 사용하는 것을 고려하는 방식으로 속도에 대한 이점을 챙겨볼 수 있다.
> 
> - 처음 보는 제어자라 찾아보니 native, strictfp, synchronized, transient, volatile 이라는 처음보는 제어자들이 존재했다.
> - 메서드 인라이닝의 경우 함수의 호출을 줄여 시간적 이점을 가져가는 기술로 함수의 실행시간이 매우 짧을 것으로 예상될 경우 괜찮은 방법으로 보이지만 디버깅이 어려울 수 있고, 함수의 의미를 파악하기 어려울 수 있으니 시기적절하게 사용하자

메서드 인라이닝이라는 기술을 처음 들어서 구글링해 보았습니다. 자바에서의 예시를 찾기 힘들었지만, 메소드 호출이 필요없는 경우 JVM에서 자동으로 메소드를 상수로 교체하여 호출 횟수를 줄이는 것으로 이해했는데 맞을까요? 혹시 아니라면 정정을 부탁드립니다!
함수의 의미를 파악하기 어려울 수 있는 점에 대해서도 연상이 잘 되지 않아서 추가 설명을 해주신다면 감사하겠습니다.

**Comment by FickleBoBo** [comment]
생각해 볼만한 좋은 질문에 감사드리며 깊게 찾아보지 않고 자료를 해석에 올렸던 점에 사과드립니다. 

저는 해당 자료를 찾을 때까지만 해도 메서드 인라이닝에 대해 다른 메서드를 호출하는 메서드가 존재할 때, 다른 메서드를 호출하지 않고 리턴을 할 수 있도록 구현해 메서드의 호출에 소모되는 자원을 줄이거나(람다식, max() 대신 삼항 연산자 활용 등) final 키워드를 통해 리턴 값을 갖는 메서드를 호출할 때 해당 리턴 값을 상수로 갖고 있다가 리턴해 자원 소모를 줄이는 것으로 이해했었습니다.(당시에는 final 이라 오버라이딩이 안돼서 리턴 값이 일정하기 때문으로 이해했었는데, final이 붙어도 리턴 값이 달라질 수 있는지를 고려하지 못했습니다.)

하지만 자료들을 두루두루 찾아보며 C++에서는 inline이라는 키워드를 통해 메서드 인라이닝이 가능하며, 이때의 결과는 컴파일 과정에서 컴파일러가 해당 메서드의 코드를 호출된 위치에 삽입하여 호출과정에 소모되는 자원을 줄인다는 것을 알게 되었습니다. 추가로 자바에서는 메서드 인라이닝이 없다는 게시글(블로그..)과 JVM이 자동으로 해준다는 글(블로그..)을 보게 되며 저 역시 개념적으로 헷갈리기도 하고 부끄러움을 느낍니다. 

자료들을 찾아보며 저는 메서드 인라이닝의 개념이 무엇이며 어디까지 적용되냐로 생각했습니다. 
먼저, 메서드 인라이닝이 개발자가 컴파일러에게 메서드 호출을 억제하도록(호출 대체) 한다면 자바에서는 해당 기능을 지원하지 않는 것으로 생각됩니다. 
다음으로, 메서드 인라이닝이 함수 호출을 최소화하는 기법으로 생각한다면 개발자의 역량에 따라 구현 가능한 테크닉의 일종으로 생각되며, 이 경우 메서드 호출 관계뿐만 아니라 final 키워드에 대한 이해가 더 필요할 것 같습니다. 
JVM이 메서드 인라이닝이 가능한 코드에 대해 자동으로 처리해주는 공식적인 글은 찾지 못해서 확답을 드리기는 어렵지만 final 키워드로 인라이닝이 가능하다면 이 부분이 해당하지 않을까 조심스럽게 생각합니다. 

함수의 의미를 파악하기 어렵다는 말은 저는 가볍게 이해하고 넘어간 파트였는데, 원하는 결과를 얻기 위해 1개의 메서드가 다른 메서드를 리턴하는 코드를 작성했을 때, 메서드 인라이닝을 적용해 리턴하는 함수 대신 어떠한 코드를 작성했을 때, 리턴에 메서드가 있었던 원래의 코드보다 사람이 이해하기 어려운 코드가 된다는 의미로 받아드렸습니다. 

```java
static int getMax1(int a, int b) {
        return Math.max(a, b);
    }

    static int getMax2(int a, int b) {
        int n;
        return n = a > b ? a : b;
    }
```
예시가 부적절 할 수 있지만 메서드가 더 복잡할 경우 위쪽 메서드 아래쪽 메서드보다 가독성이 좋지 않냐로 받아드렸습니다.

**Comment by clare-u** [comment]
헉 저는 https://www.baeldung.com/jvm-method-inlining 와 같은 글들을 읽어보며 자바에서도 메서드 인라이닝이라는 걸 하는구나 라고 이해했는데 저도 혼란이 오네요! 저도 공식적인 글을 찾게 되면 꼭 공유하겠습니다. 

함수 의미 파악 관련 예시 코드 감사드립니다. 확실히 가독성의 차이가 보여 이해가 잘 되네요!
