### ISSUE TITLE
[MEJ-002]static 과 private에 대한 질문

### ISSUE THREAD

**Issue by ssh2957** [Glenn-syj/more-effective-java#38]
Based on: #35 by @undeadtimo

저도 정적 필드와 정적 메서드가 왜 객체 지향에 부합하지 않은지 궁금했지만 다른주제가 더
궁금하여 그것에 집중하였는데 덕분에 static이 자바의 객체지향성을 어떻게 해치는지 알게 되었습니다. 

글을 읽으면서 궁금한 점이 생겼습니다. static을 활용한 정적변수는 전역 스코프로 모든곳에서
접근이 가능하다면 private static 을 통하여 전역이 아닌 제가 지정한 곳에서만 접근이 
가능하게 한다면 이는 정보를 숨길수 있으니깐 캡슐화에 부합하게 변했다고 할 수 있을까요?
저는 public을 통하여 외부로 부터 정보 보호를 받을수 있게되었으니 캡슐화에 부합하다고 생각하는데
창용님의 의견이 궁금합니다.

**Comment by undeadtimo** [comment]
ssh2957 님의 생각에 저도 동의합니다.

static 변수에 private으로 접근을 제한해주면 외부에서 변수를 가져오거나 수정하는 것이 불가능해지기 때문에 정보은닉이 가능해져 캡슐화에 부합하게 변했다고 볼 수 있습니다.

제가 쓴 글에서 지칭하는 static 의 단점은 private으로 접근이 제한되지 않은 static의 대한 것이었습니다. 설명이 부족했던 부분을 집어주셔서 감사합니다.

추가적으로 말씀드리면, 해당 static 변수에 private으로 접근을 제한하는 것 뿐만 아니라, final 로 변수를 선언해주면 static 변수의 상태를 추정하는 것이 더 쉬워지고 인스턴스를 한 번 생성한 이후 재사용하여 메모리를 절약하는 장점까지 취할 수 있습니다.

**Comment by ssh2957** [comment]
final선언을 통해 메모리를 절약하는 방법까지 알려주셔서 감사합니다! static final private등 다양한 제약사항들을 공부할수있는 글이여서 좋았습니다.
