### ISSUE TITLE
[MEJ-002]불변과 가변에 대한 질문

### ISSUE THREAD

**Issue by ssh2957** [Glenn-syj/more-effective-java#39]
Based on: #34 by @clare-u 

글을 읽고 가변과 불변에 대한 개념을 복습하고 정적 분석과 동적 분석, 캐싱등 새로운 개념을 
알게 되었습니다. 특히 final의 장점을 잘 몰랐었는데 이번 기회에 final에 대해 공부 하는 계기가 되었습니다.

글을 읽으면서 궁금한 점이 생겼습니다. "객체가 변경 가능한 데이터를 많이 가지고 있는 경우엔 불변이 오히려 부적절한 경우가 있다."
라는 문장의 뜻이  클래스의 필드에 가변과 불변의 매개변수가 섞여 있다는 것인가요?

그뒤에 객체의 불변 여부는 "외부에서 그 필드를 변경하는 방법이 존재하면 안되며 또 가변적인 필드를 접근하는 방법도 있어서는 안된다"
고 되어있습니다. 그럼 불변 객체에 가변적 필드의 여부는 상관 없다는 뜻인데 객체에 가변 불변인 데이터가
섞여 있는게 왜 부적절한 경우라고 뜻하는지 모르겠습니다.

**Comment by clare-u** [comment]
제가 과하게 요약하다 보니 설명이 난해해진 것 같아서 위키피디아의 예시 코드와 설명을 인용해 보겠습니다.

https://ko.wikipedia.org/wiki/%EB%B6%88%EB%B3%80%EA%B0%9D%EC%B2%B4

우선 불변이란, 객체가 컴퓨터의 메모리 내에서 쓰기를 할 수 없다는 뜻이 아니다. 오히려 **불변은 컴파일 시의 문제이며, 프로그래머가 「무엇을 해야하는가」 이지 반드시 「무엇이 가능한가」가 아니다.**

불변의 전형적인 예는 String 클래스의 인스턴스다.
```java
String str = "ABC";
str.toLowerCase();
```
메서드 toLowerCase()는 변수 str의 값 "ABC"를 변경하지 않고 대신 새로운 String 객체가 생성되고 생성 시 "abc"라는 값이 주어진다. 이 String 객체에 대한 참조는 toLowerCase() 메서드가 반환한다. 변수 str에 값 "abc"를 갖게 하고 싶다면 아래와 같이 작성한다.

```java
str = str.toLowerCase();
```
String 클래스에는 인스턴스의 데이터를 변경하는 메서드가 없다.

객체가 불변하기 위해서는 가변적 필드가 있는지 여부와 별개로, 외부에서 그 필드를 변경하는 방법이 존재하면 안되며 또 가변적인 필드를 접근하는 방법도 있어서는 안된다.
가변 객체의 예
```
class Cart<T> {
  private final List<T> items;

  public Cart(List<T> items) { this.items = items; }

  public List<T> getItems() { return items; }
  public int total() { /* return sum of the prices */ }
}
이 클래스의 인스턴스는 불변적이지 않다. 왜냐하면 인스턴스화 할 때 전달한 List 객체를 어딘가에서 보유하는 것으로 필드가 변경될 가능성이 있으며 getItems()를 호출해 가변적인 items 필드에 접근할 수 있기 때문이다. 아래 ImmutableCard 클래스는 부분적으로 불변하도록 작성한 예이다. (불변, 가변 겸용)
```
class ImmutableCart<T> {
  private final List<T> items;

  public ImmutableCart(List<T> items) {
    this.items = Arrays.asList(items.toArray());
  }

  public List<T> getItems() {
    return Collections.unmodifiableList(items);
  }
  public int total() { /* return sum of the prices */ }
}
```
---
이전에 작성한 Java 코드가 불변할 수 없는 이유는 또 있는데 클래스를 상속할 수 있다는 것에서 기인한다. 서브 클래스에서 멋대로 items를 변경하는 setter 메서드가 구현될 수 있다.
따라서 class에 final 수식자를 부여한다. 혹시 모르니 메서드 인수에도 final 수식자를 부여한다. 이어서 "방어적 복사"라는 기법을 이용해 getItems()에서 반환 받은 List가 변경되더라도 ImmutableCard 클래스가 보유하는 items 필드의 내용이 변경되지 않도록 복사한다. 위에서는 List를 배열로 변환하고 되돌리는 방법이 사용됐지만 여기에서는 Object.clone(Object) 메서드를 이용해 해결한다.

```
final class ImmutableCart<T> {
  private final List<T> items;

  public ImmutableCart(final List<T> items) {
    //방어적 복사한 뒤 리스트 요소의 실행 시 타입 검사를 한다.
    //리스트의 요소를 final로 한다.
    this.items = Collections.unmodifiableList(
      Collections.checkedList(
        (List<T>) items.clone(), T.class
      )
    );
  }

  public List<T> getItems() {
    // 내부 필드의 방어적 복사
    return (List<T>) items.clone();
  }
  public int total() { /* return sum of the prices */ }
}
```
인수의 객체를 일단 clone()으로 복사하고 나서 필드에 대입함으로써 인수에 전달되기 전의 List 객체와 참조를 떼어 낼 수 있다. 따라서 인수에 전달되기 전의 List 객체를 변경해도 ImmutableCard에 있는 List 객체 items까지 영향이 미치지 않는다. 방어적 복사는 getItems() 메서드에서도 할 필요가 있다. 추가적으로 코드를 설명하자면 Collections.checkedList(List<T>, Class<T>)는 items가 다른 메서드에 전달 됐을 때 리스트에 T와 다른 타입이 대입 되는 것을 막기 위해 사용한다. Collections.unmodifiableList(List<T>)는 리스트의 요소를 변경하지 못하도록 final 하기 위해 사용한다.

**Comment by clare-u** [comment]
> 그럼 불변 객체에 가변적 필드의 여부는 상관 없다는 뜻인데 객체에 가변 불변인 데이터가 섞여 있는게 왜 부적절한 경우라고 뜻하는지 모르겠습니다.

내부에서 사용하는 속성이 변화해도 외부에서 그 객체의 상태가 변하지 않은 것처럼 보인다면 불변 객체로 칭합니다. 하지만 객체가 변경 가능한 데이터를 많이 가지고 있는 경우엔 불변이 오히려 부적절한 경우가 있다고 합니다. 불변 객체는 객체를 복제할 때 객체 전체가 아니라 단순히 참조만 복사하고 끝납니다. 참조는 보통 객체 그 자체보다 훨씬 작아서, 메모리가 절감되며 프로그램의 성능에도 좋습니다. 다만 가변 데이터는 참조 복사 기법으로 다루기 곤란한데요, 가변 객체의 참조를 가지고 있는 어떤 장소에서 객체를 변경하면 참조를 공유하는 모든 장소에서 그 영향을 받기 때문입니다. 이런 경우 비용은 조금 들지만 참조가 아닌 객체 전체를 방어적 복사(defensive copy,  객체의 복사본을 만들어서 반환) 하여 대응 가능합니다.
