### ISSUE TITLE
[MEJ-002] 불변 객체의 특성에 대한 질문

### ISSUE THREAD

**Issue by FickleBoBo** [Glenn-syj/more-effective-java#40]
불변 객체에 대한 개념 설명을 통해 성능 개선에 대해 생각해 볼 수 있는 좋을 글이었습니다!! 불변 객체라는 단어를 교재에서 봤을 때, 자바의 정석에서 봤던 리터럴(literal)이라는 개념과 동일하다고 생각했는데, 불변 객체가 더 상위 개념인 것인지(사용자 정의 객체?도 포함하므로), 혹은 서로 별개의 개념인 것인지 다시 공부를 해봐야겠다는 생각이 들었습니다. 

item06 심화 탐구에서 불변 객체에 대한 설명을 보며 '객체가 불변하기 위해서는 가변적 필드가 있는지 여부와 별개로, 외부에서 그 필드를 변경하는 방법이 존재하면 안되며 또 가변적인 필드를 접근하는 방법도 있어서는 안된다'를 보며 약간 헷갈리는 부분이 있어서 질문 드립니다. 

1. 정확한 비유는 아닐 수 있지만 캡슐화를 진행한 클래스에서 setter가 없는 객체와 유사한 개념으로 받아드려도 될지 궁금합니다.
2. 또, 문장에서 '외부에서 그필드를 변경하는 방법'과 '가변적인 필드를 접근하는 방법'이 같은 말씀을 하신 것인지 궁금합니다. 
(저는 가변적 필드의 여부를 멤버 변수에 대한 final 키워드 유무 / 외부에서 그 필드를 변경하는 방법과 가변적인 필드를 접근하는 방법을 setter 메서드로 이해했습니다.)

**Comment by clare-u** [comment]
승호의 질문을 답변하면서 저도 더 이해가 깊어졌는데, 저는 리터럴보다 상위 개념이라고 이해했습니다. 2번 질문과 함께 https://github.com/Glenn-syj/more-effective-java/issues/39#issuecomment-2030803371 이곳의 답변을 함께 읽어주시면 이해에 더 도움이 될 것 같습니다.

> 1. 정확한 비유는 아닐 수 있지만 캡슐화를 진행한 클래스에서 setter가 없는 객체와 유사한 개념으로 받아드려도 될지 궁금합니다.
위의 링크(위키피디아 설명 인용)에서 내부에서 사용하는 속성이 변화해도 외부에서 그 객체의 상태가 변하지 않은 것처럼 보인다면 불변 객체로 칭한다고 합니다. 따라서 유사한 개념이라고 생각합니다. 



> 2. 또, 문장에서 '외부에서 그필드를 변경하는 방법'과 '가변적인 필드를 접근하는 방법'이 같은 말씀을 하신 것인지 궁금합니다.

저도 읽으면서 접근은 조회를 말하는 것인가 하고 넘어갔었는데, 코드 예시를 보니 둘 다 setter와 유사한 개념을 칭하는 것이 맞는 것 같습니다! 짚어주셔서 감사드립니다. 

가변 객체 코드에서 `getItems()` 를 통해 접근 가능하다고 칭하고 있네요.
```
class Cart<T> {
  private final List<T> items;

  public Cart(List<T> items) { this.items = items; }

  public List<T> getItems() { return items; }
  public int total() { /* return sum of the prices */ }
}
```
