### ISSUE TITLE
[MEJ-002] assert와 Assertion Error에 대한 보충 설명

### ISSUE THREAD

**Issue by Glenn-syj** [Glenn-syj/more-effective-java#42]
based on: #34 by @clare-u 

### 들어가며

이펙티브 자바 내 글에 기반해, 심화 탐구로 `AssertionError`에 대해서 작성해주셨는데요. 사실 `AssertionError` 에러는 `assert` 키워드와 함께 생각해보면, 이해하기에 더 좋을 것 같습니다. `assert`는 기본적으로 다음과 같은 형식으로 이용할 수 있습니다.

`assert Expression1;` 혹은 `assert Expression1 : Expression2`입니다. 여기에서 Expression1은 불리언 값을 반환하는 표현식이고, Expression2는 예외 시 발생하는 `AssertionError`에 들어갈 세부 메시지입니다. 

'Assertion'이라는 단어에 대해 설명해주신 바와 같이, `assert` 키워드는 Java에 한정하자면 변수의 값을 검증하는 데에서 이용됩니다. 아래 코드를 보시면, `AssertionError`의 사용법으로 소개하신 부분이 더 잘 이해되실 겁니다. (출처: https://www.baeldung.com/java-assert)

1. `AssertionError()`를 이용하는 `assert` 키워드

```java
public void setup() {
    Connection conn = getConnection();
    assert conn != null;
}
```

2. `AssertionError(Object detailMessage)`를 이용하는 `assertion` 키워드

```java
public void setup() {
    Connection conn = getConnection();
    assert conn != null : "Connection is null";
}
```

또한, `AssertionError`는 예외적인 상황에 대한 처리가 아니라 복구할 수 없는 상황에 대한 검증을 던져야 하는 오류입니다. 따라서 예외 처리가 필요하지 않으며, 그 의미가 퇴색됩니다.

추가로, 오라클 공식 문서에서는 코드에 `assert`를 이용해야 하는 상황에 대해서 (1) Internal Invariants (2) Control-Flow Invariants (3) Preconditions, Postconditions, and Class Invariants로 소개하고 있습니다. 이를 한 번 천천히 읽어보셔도 좋을 것 같습니다! 

### References

https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html#usage
https://www.baeldung.com/java-assert

**Comment by clare-u** [comment]
그러고 보니 `AssertionError`가 있으려면 당연히 `assert` 키워드 자체가 따로 있었겠군요! 코드로 표현해주신 예시 감사합니다. 예외 처리의 느낌으로 사용하는 게 아님에 주의해야겠습니다. 달아주신 공식 문서도 천천히 습득해보도록 하겠습니다.
