### ISSUE TITLE
[MEJ-002] Number 클래스의 xxxValue() 메서드들에 관한 추가 조사

### ISSUE THREAD

**Issue by yngbao97** [Glenn-syj/more-effective-java#43]
Based on: #32 by @FickleBoBo 
`item06 - 박싱과 래퍼 클래스의 개념 및 활용`

기본 자료형을 참조형(객체)으로 사용할 수 있도록 하는 래퍼클래스에 대해서 깊이 탐구해주셔서 풍성하고 흥미로웠습니다. 
이전까지는 사용하려는 자료구조의 제네릭 타입으로 기본 자료형을 사용하려고 하면 빨간줄이 떠서 별다른 탐구없이 자연스럽게 래퍼클래스를 사용하고 있었는데, 이번 글을 읽고 래퍼클래스 존재이유와 사용법에 대해 조금 더 이해할 수 있었습니다.
자바에서 자동으로 처리해주고 있어서 의식하지 못했던 박싱과 언박싱의 개념에 대해서도 알 수 있어서 좋았습니다.

>Number 클래스의 메서드는 기본자료형Value() 의 꼴인데 byteValue()와 shortValue()는 Modifier and Types(제어자와 자료형)가 각각 byte와 short인 반면, 다른 자료형에 대해서는 abstract 키워드 달려있었다.

이부분이 궁금해서 저도 API 문서를 읽어보았습니다.
Number 클래스의 추상메서드인 intValue(), longValue(), floatValue(), doubleValue() 는 각각의 래퍼클래스에서 필드에 자기자신의 기본자료형으로 선언된 값을 그대로 반환하기 위해(반환과정이 다름) '구현'이 필요했던 것 같습니다.

>내 생각에는 Number 클래스의 abstract intValue()를 Integer 클래스의 intvalue()에서 구현하고 이걸 타입 캐스팅한걸 byteValue()와 shortValue()에서 반환해서 둘 메서드만 abstract가 필요가 없었던 것 같다.

반면, shortValue()와 byteValue()는 추측하신 바와 같이 각 래퍼클래스가 자기자신의 자료형으로 가지고 있는 value값을 그대로 변환하지 않고 intValue() 메서드를 통해 int형으로 먼저 변환한 후 사용되도록 약속했기 때문에 각 하위 클래스별로 구현할 필요가 없습니다.

>This implementation returns the result of intValue() cast to a byte

문서에서 이부분 앞에 `@implSpec`라는 주석이 포함되어 있는데, 이 문서화 주석은 해당 메서드와 하위 클래스 사이의 계약을 설명한다고 합니다.

더 찾아보니 잘 이해해서 적어주신 것 같아 의견에 힘을 싣고자 추가 조사를 통해 이해한 내용 공유드렸습니다. 감사합니다!
<hr>
- 레퍼런스  

[문서화 주석관련](https://incheol-jung.gitbook.io/docs/study/effective-java/undefined-6/56-api)

**Comment by FickleBoBo** [comment]
좋은 탐구 감사합니다. 
제네릭에도 래퍼클래스가 들어간다는 부분을 놓치고 있었는데, 컬렉션을 사용할 때 자료의 입출력 과정에서 오토박싱이 이루어지는지 등등 좀 더 알아봐도 재밌을 것 같습니다.
