### ISSUE TITLE
[MEJ-002] 싱글턴 패턴과 모킹에 대한 글을 읽고

### ISSUE THREAD

**Issue by undeadtimo** [Glenn-syj/more-effective-java#44]
based on: #[link](https://github.com/Glenn-syj/more-effective-java/blob/glenn-syj/chapter_02/item03_%EC%86%90%EC%98%81%EC%A4%80_%EC%99%9C-%EC%8B%B1%EA%B8%80%ED%84%B4%EC%9D%80-%EB%AA%A8%ED%82%B9%EC%9D%B4-%EC%96%B4%EB%A0%A4%EC%9A%B4%EA%B0%80.md) by @Glenn-syj 

작성하신 글 잘 읽었습니다.

저는 같은 부분을 읽었을 때, 모킹이란 단어의 뜻을 이해하지 못한 채로 넘어갔으며,
test에 대한 개념 또한 프로그램을 실행하여 의도한 기능이 올바르게 작동하는지 확인하는 것으로만 이해하였습니다.

그러나 Glenn-syj 님이 작성하신 글을 보고 프로그램의 최소 기능 단위인 unit에 대해 알게 되었으며,
또한 본문에서 언급하는 test란 최소 기능 단위인 unit을 테스트하는 unit test임을 알게 되었습니다.

더불어 모킹이란 의존관계가 존재하는 프로그램에서 unit test를 위해 사용할 수 있는 것으로,
모방 객체인 목(Mock)을 만드는 것임을 알았습니다.

하나 궁금한 점은, 작성하신 글에서 보여준 모킹 방식과 실제, Junit에서 Mockito를 사용했을 때의 기능상 차이점이 존재하는가 입니다.

글을 보고 Mockito에 대해 찾아보았으나, 쉽게 Mockito에 대해 파악하기 쉽지않아 대략적인 설명을 해주신다면 이해하기 쉬울 것 같습니다.

**Comment by Glenn-syj** [comment]
"기능 상"이라는 기준이 어떤 측면에서의 기능인지 모르겠습니다. 하지만 일단 답할 수 있는 부분은 test framework 와 manual test code가 가지는 차이일 건데요. 당연하게도 이는 프레임워크가 갖는 장점과 동일할 수 밖에 없습니다.

프레임워크의 이용은 manual code에 비해 코드 효율성과 안정성을 높이고, 유지보수를 용이하게 만듭니다. 또한, 휴먼 에러가 발생하는 부분을 자동화할 수도 있고요. 게다가 수많은 테스트 예시를 직접 작성해야한다고 생각하면, manual code는 좋은 선택이 아닌 것 같습니다. 물론, 프레임워크 내부의 기능으로 만족할 수 없는 경우에는 추가적인 작업이 필요하겠지만요.

예를 들어, 모킹 코드를 직접 작성하는 대신 Mockito는 `@Mock`, `@DoNotMock`, `@InjectMock`과 같은 어노테이션을 통해 모킹을 쉽게 수행하고 관리할 수 있게 해줍니다. JUnit도 마찬가지로 어노테이션을 통해 인스턴스를 생성하고, 실행 시점을 관리할 수 있습니다.

**Comment by Glenn-syj** [comment]
```java
// https://stackoverflow.com/questions/68424864/how-does-junit-test-work-in-the-background
class Test{
   private  String hello = "";

   @Test
   void test1() {
      hello = hello + "1";
      System.out.println(hello);
   }
   @Test
   void test2() {
      System.out.println(hello)
   }
}
```
위와 같은 JUnit 어노테이션을 이용한 코드가 있을 때, 사실 그 실행 세부과정은 다음과 같다고 합니다.

```java
// https://stackoverflow.com/questions/68424864/how-does-junit-test-work-in-the-background

Test test = new Test();

test.test1();

...

test = new Test();

test.test2();
```

여기에서 물론 `test1()`과 `test2()`는 큰 차이가 없습니다. 해당 질문에 대한 조사를 위해 제가 쓴 글이기는 하지만, 레퍼런스 파트나 추가적인 이해가 궁금하신 점이 있다면 읽어주셔도 좋겠습니다!

https://github.com/Glenn-syj/TIL/blob/master/Spring/240402_Spring_Why-do-we-use-Mockito-and-JUnit.md

**Comment by undeadtimo** [comment]
질문에 대한 답변 감사합니다.

제 질문이 포괄적인 부분에 대한 것이다보니 Glenn-syj님께서 특히 많은 조사를 하신 것이 보이네요.

저로서는 일반적인 프레임워크에 대한 지식이 부족하다보니, 처음 Junit, Mockito를 보았을 때, 
일반적인 프레임워크가 갖는 장점을 바로 떠올리지 못해 특별한 무언가가 존재할 것이라고 생각하였습니다.

Glenn-syj님의 답변을 보고 알게된 것을 정리하자면, 
일반적인 프레임워크가 갖는 장점처럼 Junit의 Mockito 또한 프로그래머의 사소한 실수로부터 발생하는 human error를 방지하고 그 과정을 단축시켜 효율성을 높이는 효과를 갖고 있습니다.

특히, 실행 순서에 대한 우선순위를 동일하게 만드는 부분이나, `@BeforeClass`, `@BeforeAll`, `@AfterEach` 어노테이션을 통해 테스트가 실행되는 시점을 정할 수 있는 부분을 보고 Mockito를 사용했을 때의 효율성이 막대할 것임이 예상되었습니다.

앞으로 다양한 프레임워크에 익숙해지는 것이 목표였는데, 해당 답변 덕분에 현재 공부하는 spring 외에 junit의 Mockito에 대한 구체적인 사용법과 이론을 터득해볼 수 있을 것 같습니다
