### ISSUE TITLE
[MEJ-002] 의존성 주입 방식 중, 생성자 주입과 setter 주입에 대해.

### ISSUE THREAD

**Issue by undeadtimo** [Glenn-syj/more-effective-java#45]
based on: #33 by @ssh2957 

ssh2957님이 작성하신 글 잘 읽었습니다.

의존성이라는 개념과 의존성 주입이라는 말을 막연하게만 이해하고 있었는데 해당 글을 읽고 이해할 수 있게 되었습니다.

의존성이란 '외부'에서 객체나 프로세스를 제공받아 외부에 '의존'한다는 것이고,

의존성 주입이란 의존관계로 연결되어 있는 두 모듈이 서로 영향을 끼칠 수 있기 때문에, 그런 여파를 줄이기 위해 따로 의존 관계를 맺어 객체나 프로세스를 제공할 주입자를 만들어주는 것을 의미하는 것을 알게되었습니다.

하나 궁금한 점은, ssh2957님이 작성하신 글에서 나온 생성자 주입과 setter 주입 중 어떤 방식이 더 효율적인가 입니다.

생성자 주입 방식을 사용하면, 인스턴스가 생성되는 그 시점에 의존성이 주입된다는 것은 알지만 그것이 좋은 것인지 setter 주입 방식과 비교하면 어떻게 더 기능적으로 좋은 것인지는 이해하지 못하였습니다.

ssh2957 님께서 추가적인 설명을 해주신다면 이해하는 데 도움이 될 것 같습니다.

**Comment by ssh2957** [comment]
생성자와 setter 주입방식의 차이점
setter에만 집중하다 보니 생성자주입에 대한 설명이 부족했던것 같습니다. 생성자주입과 setter주입의 정의와 차이점 그리고 장단점 까지 찾아보았습니다. 
설명:
생성자 주입을 사용할 때 필요한 모든 종속성은 생성자를 통해 제공되어야 합니다. 나중에 주입할 수 있도록 설정자가 있어서는 안 되기 때문입니다.(private로 막혀 있기 때문) 따라서 인스턴스에는 필요한 모든 종속성이 있습니다
Setter 주입을 사용하면 생성 인스턴스가 있을 수 있지만 필요한 종속성이 모두 없을 수 있습니다(setter를 통해 설정되지 않았기 때문입니다). 사용자는 필수 종속성을 설정하지 않고도 개체를 사용할 수 있습니다.

생정자 주입의 장점: 
1. 생성자 주입은 클래스 에서 종속성을 명시적이고 가시적으로 만들어 코드 가독성을 향상시킵니다.(인스턴스 생성 단계에서 어떤 정보가 들어가는지 볼 수 있다.)
2. 일단 주입되면 종속성이 불변인 경우가 많아(생성자 주입을 사용할때는 종속성이 변하지 않는 경우에 사용하는 경우가 많다! ) 안정적이라고 합니다. 

단점:
복잡성: 어떤 경우에는 매개변수가 많은 생성자가 다루기 어려워질 수 있습니다. 

setter 주입 방식의장점 
유연성: 종속성을 보다 유연하고 동적으로 주입할 수 있습니다.(언제든지 setter를 통해 정보 주입 가능)

단점 
가시성: 종속성은 클래스에서 명시적으로 표시되지 않으므로 코드 가독성에 영향을 미칠 수 있습니다.(처음에는 정보를 안넣어주고 언제 setter를 통해 넣어주는지 찾아 봐야함 )
가변성: 객체의 상태는 생성 후에 변경될 수 있으며 잠재적으로 예측 가능성이 낮고 스레드로부터 안전한 디자인으로 이어질 수 있습니다.

만약 의존성 주입 단계에서 모든 정보를 다 가지고 있다면 생성자 주입을 통해 정보를 가진 인스턴스를 생성해 주는게 보편적이고
필드의 틀만 가지고 있다면 정보가 없는 인스턴스를 생성후 Setter주입방식을 통해 나중에 정보를 주입 시켜주면 됩니다.


참조
https://stackoverflow.com/questions/33361027/constructor-injection-vs-setter-injection
https://www.tutorialspoint.com/difference-between-constructor-injection-and-setter-injection-in-spring

**Comment by undeadtimo** [comment]
우선 ssh2957님의 정성스런 답변에 감사드립니다.

처음 생성자 주입 방식을 보았을 때는 인스턴스가 생성되는 시점에 의존성이 주입되는 것이 어떤 효과로 이어지는지 이해하지 못하였지만, ssh2957님의 답변을 통해 생성자 주입 방식의 장점에 대해 이해하게 되었습니다.

뿐만 아니라, 생성자 주입 방식을 setter 주입 방식과 비교하여 장단점을 깔끔하게 정리해주어 한결 차이점을 받아들이기 편하였습니다.

ssh2957님의 답변을 통해 알게 된 것을 정리하자면,

생성자 주입은 코드 가독성과 안정성을 중요시하고, 또한 의존성 주입 단계에서 생성자를 구성하는 정보들이 갖춰져있을 때 사용하기 용이하다는 것을 알게 되었고.

setter 주입은 매개변수가 너무 많아서 복잡한 경우, 또는 종속성 주입을 객체 생성 단계가 아닌 다른 시점에서 하고자 할 때 용이하다는 것을 알게 되었습니다.

spring framework를 공부하며 의존성에 대해서도 배웠지만, 해당 개념에 대해 깊숙한 이해는 못하고 있었으나 ssh2957님의 구체적인 설명 덕분에 의존성에 대해 깊이 있는 이해를 하게 되었습니다.
