### ISSUE TITLE
[MEJ-002] 클래스 인스턴스화 방지를 위한 보다 확실한 방법에 대해

### ISSUE THREAD

**Issue by yngbao97** [Glenn-syj/more-effective-java#46]
Based on: #33 by @ssh2957 
`item04-추상클래스로 인스턴스화 막아보기`

추상클래스로는 인스턴스화를 막을 수 없다는 필자의 주장을 의심해보고 직접 테스트 해본 점이 좋았습니다. 아쉽다고 적어주신대로 아직 저도 아는게 많지 않아서 private 외에 인스턴스화를 막을 수 있는 다른 방법에 대해 떠올릴 수 없었습니다..

써주신 글을 토대로 추가 조사를 하다보니, 인스턴스화를 막기위해 추상클래스를 사용한다는 의견도 많이 있더라구요.   
그런데 책에서 말한 것처럼 해당 추상클래스 자체를 인스턴스화 할 수 없을 뿐, 상속 클래스(하위클래스)로는 인스턴스화가 가능하다는 허점이 존재했습니다.

여기서 저는 반대로 private 생성자로 인스턴스화를 완전히 막을 수 있는가에 대해서도 의문이 들었습니다. 왜냐하면 item3(p.23)을 읽을 당시, private 생성자에도 예외가 있다고 적혀있었기 때문입니다. (리플렉션 API)

```java
Class<Member> aClass = Member.class;
Constructor<?> constructor = aClass.getDeclaredConstructor();
// 생성자 가져오기

Object object = constructor.newInstance();
// 이렇게 인스턴스를 생성할 수 있다.

Member member = (Member) constructor.newInstance();
// 타입 캐스팅을 사용해서 위와 같이 받아올 수 있다.
```
예시 코드 출처 : [hudi.blog](https://hudi.blog/java-reflection/)

이 또한 접근 권한이 있어야 private 생성자에 접근할 수 있는 것이지만, 확실한 방지를 위해서는 단순히 생성자를 private으로 선언하는 것 외에 한가지 단계를 더 추가할 수 있습니다. 

```java
public class Member {
    private Member() {
        throw new NullPointerException("너한테 줄거 없다");
    {
}
```
예외의 상황에서라도 생성자에 접근하려고 하면 위 예시 코드와 같이 exception을 던지는 것입니다.

조금 다른 관점이지만 함께 알아두면 좋을 것 같아 추가로 공부한 내용 공유드렸습니다. 감사합니다!

<hr>
- 레퍼런스

[java.lang.reflect 의 Constructor 클래스 공식문서](https://docs.oracle.com/javase/7/docs/api/)

**Comment by ssh2957** [comment]
private 생성자에도 헛점이 있다는것만 알았지 직접 구현을 하지않고 리플렉션 API라는것이 있구나~ 라고만 생각했는데 
yngbao97님의 예시 코드덕분에 이해가 잘된것 같습니다. 감사합니다.
