### ISSUE TITLE
[MEJ-002] 의존성 주입의 예시에 대한 질문

### ISSUE THREAD

**Issue by FickleBoBo** [Glenn-syj/more-effective-java#47]
붕어빵과 속의 관계를 통해 의존성 주입에 대한 설명을 해주시고, 이를 확장하려는 심화 탐구를 통해 기존에 생각하지 못한 많은 부분을 다시보게 되는 시간이었습니다. 다만, 제가 개념적으로 부족할 수 있지만, 클래스를 통해 인스턴스를 생성함에 있어 필드에 직접 접근, 생성자 혹은 setter 등의 메서드를 이용하여 특별히 초기화를 시켜주지 않는다면 모든 인스턴스는 같은 상태값으로 초기화 될 것으로 생각됩니다. 인스턴스마다 다른 특징을 부여하고 싶다면 의존성 주입이라고 소개된 개념이 당연하게 적용되어야 하는데, 의존성 주입을 학습을 해야하는 이유에 대해 어떻게 생각하시는지 궁금합니다!

**Comment by yngbao97** [comment]
### 의존성 주입을 학습을 해야하는 이유

>필드에 직접 접근, 생성자 혹은 setter 등의 메서드를 이용하여 특별히 초기화를 시켜주지 않는다면 모든 인스턴스는 같은 상태값으로 초기화 될 것으로 생각됩니다.
> 인스턴스마다 다른 특징을 부여하고 싶다면 의존성 주입이라고 소개된 개념이 당연하게 적용되어야 하는데

모든 클래스는 인스턴스를 하나만 생성하거나, 의존객체 주입을 통해 다양한 인스턴스를 생성하는 등 각각의 목적에 따라 다양한 형태로 선언할 수 있습니다.
의존 객체 주입은 말씀하신바와 같이 인스턴스마다 다른 특징을 부여하고 싶어서 이미 당연하게 사용해오고 있는 방법이고, 그렇기 때문에 이러한 질문을 주신 것 같네요.

당연하게 사용해오고 있는 만큼 의존객체 주입을 통해 클래스의 안정성을 유지(인스턴스마다 자원이 달라진다고 해서 코드를 수정할 필요가 없음)하면서 확장성을 제고할 수 있다는 점을 확실히 인식하면 좋을 것 같아서 심화 탐구 주제로 정했습니다!
또한 주입할 자원의 타입에 대해서도 간단한 예시에서는 얼핏 당연해보이지만 큰 규모의 프로그램을 고려하면 한번 쯤 짚고 넘어갈 필요가 있다고 생각했습니다! (주입 객체의 타입의 상속/구현 관계가 정확히 구현되어야 알맞게 동작할 것이기 때문) 
감사합니다 :)
