### ISSUE TITLE
[MEJ-003] scope, WeakHashMap 예시 코드 관련 질문 및 의견

### ISSUE THREAD

**Issue by yngbao97** [Glenn-syj/more-effective-java#59]
Based on: #57 by @undeadtimo 
`메모리 관리 방법에 대해` 를 읽고
<hr>

item7을 읽으면서 변수를 유효 범위 밖으로 밀어낸다는 표현이 잘 와닿지 않았는데, 이 범위가 scope이라는 설명과 함께 코드 달아주셔서 이해에 도움이 되었습니다. 

변수를 scope 밖에 선언해서 scope이 끝나도 계속 메모리를 차지하는 예시 코드를 남겨주셨는데, 반대로 메모리 누수가 없게끔 범위 안에 선언하려면 다음과 같은 코드가 되는걸까요? 
```java
public class Test {
    public static void main(String[] args) {
        while (true) {
            Object object = new Object();
        }
    }
}
```

또 2번 WeakHaspMap에도 예시 코드를 첨부해주셨는데, assertTrue는 테스트에 사용하는 JUnit API라고 알고 있습니다.
if문이 아닌 테스트용 코드로 예시를 적어주신 이유가 있을까요? 제가 틀릴수도 있지만.. 추후 메서드 사용에 혼선이 있을지 않을까 해서요! 관련 링크 첨부드립니다!

key값을 null로 처리하는 부분이 중점이라면 assertTrue가 없거나, 참거짓 여부 판단용이라면 if문을 사용하는 편이 보다 단순하고 직관적으로 이해하기 좋을 것 같습니다! 감사합니다!

[assertTrue 메서드 사용방법 관련](https://stackoverflow.com/questions/25352329/how-to-use-asserttrue)

**Comment by undeadtimo** [comment]
좋은 질문 감사합니다.

네 yngbao97 님이 보여주신 코드대로 작성하는 것이 메모리 누수가 덜 발생하며, 변수의 범위를 최소화할 경우의 여러 장점을 얻을 수 있습니다.

반복문 내에서 변수를 생성한다고 하더라도 반복문이 끝나면 생성한 변수는 제거될 것이기에, 반복문이 끝난 이후의 메모리 누수를 방지해주면서 반복문 밖에서 변수를 생성할 때에 비해 큰 메모리 소모를 일으키지도 않습니다.

또한 반복문 내부에서 변수를 생성하는 것과 반복문 바깥에서 변수를 선언한 이후, 반복문 내부에서 변수를 초기화하는 두 방식을 비교하였을 때, 둘의 속도 차이는 '극히 미미한 수준'이었습니다.

따라서, 본문에서도 나와있듯이, 극히 미미한 수준의 메모리 사용 또는 성능 저하 보다는 scope를 벗어난 이후의 메모리 누수를 방지하기 위해 가능한한 작은 scope의 변수를 생성해주는 것이 좋습니다.

Reference :
https://stackoverflow.com/questions/8803674/declaring-variables-inside-or-outside-of-a-loop

---

제가 예시로 보여드린 코드에서 assertTrue는 단순히 참, 거짓 여부를 판단하기 위한 것으로 if 조건문으로 대체해도 무방합니다. 
yngbao97님께서 말씀해주신대로 if 조건문을 사용하여 표현하는 것이 더 직관적이어서 보는 이로 하여금 잘 이해할 수 있게 할 것 같습니다.

**Comment by yngbao97** [comment]
답변 감사합니다! 
반복문 내부에서 변수를 반복적으로 생성하는 것과 초기화 하는 것의 성능 차이에 대해서도 궁금했는데 상세히 답변해주셔서 큰 도움이 됐습니다!
덕분에 해당 부분에서는 큰 걱정 없이 메모리 누수 방지에 좀 더 집중해볼 수 있을 것 같습니다. 이번주도 고생하셨습니다👍🏻
