### ISSUE TITLE
[MEJ-003] 파싱과 split, StringTokenizer에 대한 조사

### ISSUE THREAD

**Issue by FickleBoBo** [Glenn-syj/more-effective-java#62]
Based on: #58 by @clare-u 

며칠전에 문자열은 부분문자열로 분리할 때, split()은 빈 문자열 ""를 넣으면 길이 1짜리 문자열 하나하나 구분해주는데, StringTokenizer는 안될까라고 생각했었는데, 올려주신 글을 보며 split은 메서드고 StringTokenizer는 클래스인데 애초에 같을 필요도 없구나라는 생각이 들었습니다. parseInt()와 같은 메서드들은 자주 쓰면서 parse()가 존재한다는 것도 이번에 처음 알게 되어 유익한 시간이었습니다. 

해당 글에서 영감을 받아 split()과 StringTokenizer에 대해 좀 더 알아보기로 했습니다. 
split()의 경우 이미 다들 잘 사용하시겠지만 파라미터로 받은 문자열(regex)로 해당 문자열은 구분해서 문자열 배열로 반환하는 메서드입니다. regex가 현재 문자열에 포함되지 않은 문자열이면, 원본 문자열을 그대로 문자열 배열로 반환하며, regex를 기준으로 구분할 때 regex는 포함되지 않습니다. 추가로 잘 사용할 것 같지는 않았지만 파라미터를 하나 더 받아서 split에 대한 제한을 걸 수도 있었습니다. 

```java
// 직접 작성
String[] str1 = "00101000101".split("0");
String[] str2 = "00101000101".split("0", 5);

System.out.println(Arrays.toString(str1));
// [, , 1, 1, , , 1, 1]
System.out.println(Arrays.toString(str2));
// [, , 1, 1, 00101]
```

StringTokenizer는 생성자에서 (문자열, 구분자, 구분자포함여부)를 파라미터로 받을 수 있으며, 생성자 오버로딩 구조를 보면 문자열은 필수이고 나머지는 선택할 수 있었습니다. 구분자를 생략하면 문자열을 그대로 토큰으로 넘기며, 구분자를 넣어주면 구분자를 기준으로 문자열을 토큰화합니다. 이때 split의 regex와 StringTokenizer의 구분자와의 차이점은 regex는 해당 문자열을 기준으로 분리하는 반면 구분자는 구분자에 포함된 각각의 길이 1 문자열을 기준으로 전부 분리를 합니다. 구분자포함여부는 split은 regex로 구분하고 regex는 포함되지 않는 반면 StringTokenizer는 선택 가능하다는 차이점이 있습니다. 

split()과 StringTokenizer를 찾아보며 얼핏보면 비슷한 기능을 하는 것 같았지만 목적성부터 작동 방식이 완전히 다르다는 느낌이 많이 들었습니다. 잘못된 내용에 대한 지적은 환영합니다. 

출처 : https://docs.oracle.com/javase/8/docs/api/

**Comment by clare-u** [comment]
중요한 차이점들을 잘 짚어주셔서 좋네요! 저같은 경우 부끄럽지만 parseInt() 사용에 익숙하지 않았었는데, 글 작성을 계기로 더 과감하게 사용해보려고 합니다 ㅎㅎ
