### ISSUE TITLE
[MEJ-003] hashCode 일반 규약에 대한 보충적 의견

### ISSUE THREAD

**Issue by Glenn-syj** [Glenn-syj/more-effective-java#64]
based on: #56 by @FickleBoBo 

## hashCode 일반 규약에 관하여

@FickleBoBo 님께서 작성해주신 글에서 규약 1번이 꼭 필요한 이유를 납득하지 못했다고 말씀해주셨는데요. 도움이 될까 싶어 `hashCode()` 일반 규약에 대해 추가로 학습해봤습니다.

### 내적 일관성으로서의 규약

`hashCode()` 일반 규약(hashcode contracts)가 `equals()` 메소드와 연관된다는 점은 이미 글에서 드러난 바 있습니다. [Baeldung](https://www.baeldung.com/java-equals-hashcode-contracts)에서는 일반 규약들을 간단한 용어로 표현합니다. 그 중에서 규약 1번은 내적 일관성(internal consistency)라는 말로 요약됩니다. 

- 내적 일관성 Internal Consistency
> equals 비교에 사용되는 정보가 변경되지 않았다면, 애플리케이션이 실행되는 동안 그 객체의 hashCode 메서드는 몇 번을 호출해도 일관되게 항상 같은 값을 반환해야 한다.(단, 애플리케이션을 다시 실행한다면 달라져도 상관없다.)
(인용은 @FickleBoBo 님이 chatGPT를 이용하셔서 번역한 문장입니다.)

@FickleBoBo 님께서는 오버라이딩과 같은 실천적인 방면에서 해당 규약을 파악하고 계시지만, 저는 이 문장이 말 그대로 '규약'으로서 읽혀야 한다고 봅니다. 규약으로 읽힌다는 것은 곧 미준수 시에 예상과 다르게 동작한다는 뜻이기도 하지만, 다른 규약이 성립하기 위한 조건이 된다는 뜻이기도 합니다.

### 내적 일관성 규약 뜯어보기

규약을 자세히 살펴보자면, 이는 (1) `equals()`비교에 사용되는 정보가 변경되지 않았다는 가정과 (2) `hashCode()` 메서드가 일관된 값을 반환해야한다는 결론으로 구성됩니다. 

(1) 가정은 `equals()`를 통해서 객체가 동등성을 유지함을 의미합니다. `equals()` 비교에 만약 어떠한 `Person` 객체의 `name` 속성이 쓰인다고 가정해봅시다. 만약 비교에 사용되는 `name`이 변경되지 않았다면, `age`나 `job`이 변경된다고 해도 이전과 동등한 객체로 파악해야 할 것입니다.

(2) 결론은 객체가 동등성이 유지되는 한에서는 `hashCode`에 대해서 같은 값을 반환해야 함을 의미합니다. 결론이 가지는 효용을 이해하기 위해서는 2번 규약과 3번 규약을 함께 고려해야 합니다.  2번 규약과 3번 규약은 `equals()`의 결과에 따르는 규약이기 때문입니다.

즉, 1번 규약은 2번과 3번 규약이 성립할 수 있는 바탕이 됩니다. 만약 내적 일관성이 지켜지지 않는다면 이후의 규약들은 무의미해집니다. 애플리케이션 재실행 시에는 당연하게도 객체가 소멸되고 다시 생성되기에, 이전과 반환값이 같을 필요가 없습니다.

### References

https://www.baeldung.com/java-equals-hashcode-contracts

**Comment by FickleBoBo** [comment]
(1)번 항목의 equals() 비교에서 사용되는 정보로만 객체의 동등성을 판단하고 이에 대해 동등한 객체라면 동일한 hashCode를 반환해야 한다는 말로 이해했습니다!! 클래스에서 처음 배웠던 추상화 개념과 불변 객체등을 호출할 때 새로 생성하지 않고 바로 반환하는 메서드가 섞인듯한 느낌도 드네요. 이슈를 온전히 이해할 수 있도록 노력하겠습니다!!
