### ISSUE TITLE
[MEJ-003] finalize()와 cleaner

### ISSUE THREAD

**Issue by clare-u** [Glenn-syj/more-effective-java#65]
Based on: [chapter_02/item08_손영준_네이티브-피어와-생명-주기.md](https://github.com/Glenn-syj/more-effective-java/blob/glenn-syj/chapter_02/item08_%EC%86%90%EC%98%81%EC%A4%80_%EB%84%A4%EC%9D%B4%ED%8B%B0%EB%B8%8C-%ED%94%BC%EC%96%B4%EC%99%80-%EC%83%9D%EB%AA%85-%EC%A3%BC%EA%B8%B0.md) by @Glenn-syj 

---

finalize 메서드는 더 이상 사용하지 않는다고 했지만 finalize와 cleaner는 어떤 코드를 작성하여 사용하는지 궁금해서 공식 문서를 찾아보았습니다.

우선 `finalize` 를 Override 하면 해당 객체가 JVM 에게 Garbage Collection 을 해야 할 대상이 될 때 호출되어, 객체가 없어지기 전 다른 연관 자원을 정리하려는 의도로 작성되었다고 합니다. (원래 객체는 팬텀 도달 가능(phantom reachable) 상태가 될 때, 즉 JVM에 강하거나 약한 참조가 남아 있지 않을 때 가비지 콜렉팅 대상이 됩니다)

```java
@Deprecated(since="9")
protected void finalize​()
                 throws Throwable
```

`@Deprecated` 태그를 처음 보는데 인상깊은 태그네요.. (사전적으로: 더 이상 사용되지 않음)

java9 에서는 대안으로 Cleaner 를 지원하게 되었으며, 지금으로써는 finalize 메서드의 대안으로 3가지가 있습니다. 원 글에서 언급해 주셨던 try-catch-finally 블록, try-with-resource 문, 그리고 클리너(cleaner) 입니다.

`cleaner` 코드의 예시 입니다.

```java
public class CleaningExample implements AutoCloseable {
  // A cleaner, preferably one shared within a library
  private static final Cleaner cleaner = <cleaner>;
  static class State implements Runnable {
    State(...) {
      // initialize State needed for cleaning action
    }
    public void run() {
      // cleanup action accessing State, executed at most once
    }
  }
  private final State;
  private final Cleaner.Cleanable cleanable
  public CleaningExample() {
    this.state = new State(...);
    this.cleanable = cleaner.register(this, state);
  }
  public void close() {
    cleanable.clean();
  }
}
```
close() 메서드를 명시적으로 호출해서 참조를 정리할 수 있다는 점이 GC의 (모호한) 호출에 온전히 의존하는 finalize()와 가장 큰 차이입니다. 자바의 진화가 어디까지 이루어질지 흥미롭네요!

**참고 자료**
_https://docs.oracle.com/javase/9/docs/api/java/lang/Object.html#finalize--
https://www.itworld.co.kr/news/224419
https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/lang/ref/Cleaner.html_

**Comment by Glenn-syj** [comment]
### 들어가며

`Cleaner`에 대해 잘 정리해주셔서 감사합니다. 참조에 대한 네 단계는 저도 처음 알게 되었는데요, JVM이 구성되는 방식이 더 궁금해지네요.

안 그래도 네이티브 피어를 다루면서, `close()`에 대해서만 다룬 감이 있었는데요. `Cleaner`를 사용하는 방식을 알려주셔서 네이티브 피어의 자원 회수에도 적용할 수 있을 것 같습니다. 

```java
public class CleaningExample implements AutoCloseable {
  // A cleaner, preferably one shared within a library
  private static final Cleaner cleaner = <cleaner>;
  static class State implements Runnable {
    State(...) {
      // initialize State needed for cleaning action
    }
    public void run() {
      // cleanup action accessing State, executed at most once
    }
  }
  private final State;
  private final Cleaner.Cleanable cleanable
  public CleaningExample() {
    this.state = new State(...);
    this.cleanable = cleaner.register(this, state);
  }
  public void close() {
    cleanable.clean();
  }
}
```

위 `CleaningExample`은 `AutoClosable`을 구현하고 있기에 try-with-resources 구문에서 종료 시 `close()`를 호출함으로써 `.clean()`을 이용할 수도 있다고 하네요! 

또한, `Runnable` 인터페이스는 인스턴스가 스레드에서 실행되도록 할 때 쓰이는데요. `run()` 메소드는 스레드가 시작될 때 스레드의 실행과는 별개로 호출된다고 합니다. 비동기에 대한 이해가 생기면, `Runnable` 인터페이스도 다시 한 번 조사해보겠습니다! 

### References

https://www.baeldung.com/java-destructor
