### ISSUE TITLE
[MEJ-003] equals 메서드의 구조와 엄격한 관리 형태에 대해

### ISSUE THREAD

**Issue by undeadtimo** [Glenn-syj/more-effective-java#67]
Based on: #55 by @yngbao97 

yngbao97님이 작성하신 글 잘 읽었습니다.

'이펙티브 자바' 본문에서 해당 item을 읽을 때는, 예시 코드에 처음보는 클래스와 메서드들이 존재하여 이해하기 어려웠으나 yngbao97님의 예시코드와 설명을 읽으니 본문에서 말하고자 한 것들을 제대로 이해할 수 있게 되었습니다!

최상위 클래스인 Object에 존재하는 정적 메서드 equals와 멤버 메서드 equals에 대해,

그리고 String처럼 변수의 '값'을 비교해야 하는 클래스에서는 어떤 식으로 eqauls가 오버라이딩 되는지를 이해하여,

앞으로 equals를 사용하거나 아니면 '=='를 사용할 때, 해당 로직이 어떤식으로 참조값을 비교하는지 어떤식으로 변수 값을 비교하는지 과정을 머릿속에서 그려져 한층 더 깊이있게 코드를 작성할 수 있을 것 같습니다.

또한 contains 메서드와 equals 메서드의 연관성을 인지하지 못했는데, 자주 사용하던 ArrayList 클래스의 contains 메서드가 indexOf, indexOfRange를 차례로 호출하여 마지막에 equals 메서드를 호출하는 것을 알게되어, contains 메서드의 원리를 이해할 수 있게 됐습니다.

해당 글을 읽으며 equals에 대한 것을 이해했을 뿐만 아니라, 메서드 내에서 간단한 기능 체크를 먼저 시행하는 것이 효율성 측면에서 좋다는 것을 알게 되었습니다.

```java
    // 두 객체의 주소값이 같으면 더 비교할 필요없이 같은 객체다.
    // 메서드 효율성을 위해 주소값을 먼저 비교
    if (this == anObject) {
        return true;
    }
```

사실 저는 이 글을 이해하기 위해 yngbao97님의 예시 코드를 하나씩 따라하여 보았습니다.

그러나 마지막 예시에서 str1과 str2를 Object 클래스의 equals 메서드를 가져와 비교하여 false가 출력되는 코드를 작성해보고 싶었지만, 

String 클래스는 final로 선언되어 있어 String 클래스를 상속한 이후, 다시 오버라이딩 하는 방법으로 Object 클래스의 equals 메서드를 가져오는 것이 불가능했습니다. 

```java
The type MyString cannot subclass the final class String
// String 클래스를 상속받고자 하면 이러한 메시지가 나온다.
```

이러한 결과를 통해 java에서 equals의 재정의에 대하여 엄격하게 관리하고 있음을 더욱 잘 이해하게 되었습니다.

**Comment by yngbao97** [comment]
String 클래스가 final로 선언되어 있어서 상속이 불가하다는 것은 인지하지 못했는데, 덕분에 보다 엄격한 equals 재정의 관리에 대해 저도 알 수 있었어요 감사합니다! 

> 마지막 예시에서 str1과 str2를 Object 클래스의 equals 메서드를 가져와 비교하여 false가 출력되는 코드를 작성해보고 싶었지만,

말씀하신 것처럼 String 클래스는 equals 재정의가 불가해서 제가 예시로 적어뒀던 코드로는 확실한 검증이 어려웠겠네요!
정확한 확인을 위해서 새로운 클래스를 생성해 테스트 해보았습니다.

```java
class Word {
	String value;

	public Word(String value) {
		this.value = value;
	}
}
```

위와 같이 String 자료형의 필드값을 가지고 있고, equals 메서드를 재정의 하지 않은 Word 클래스를 정의 했습니다.
이 클래스의 인스턴스들을 생성해 equals 메서드와 List의 contains 메서드를 사용해보면 결과는 다음과 같습니다.

```java
Word w1 = new Word("육예진");
Word w2 = new Word("육예진");

List<Word> list1 = new ArrayList<>();
list1.add(w1);

System.out.println(w1.equals(w2));	      // false
System.out.println(list1.contains(w2));        // false
```

하지만, 위 클래스에 equals메서드를 추가로 재정의 하게되면 결과는 모두 true로 반환하게 됩니다.

```java
@Override
public boolean equals(Object obj) {
if (this == obj)
	return true;
if (obj == null)
	return false;
if (getClass() != obj.getClass())
	return false;
Word other = (Word) obj;
return Objects.equals(value, other.value);
}
```

더 적절한 예시코드를 테스트 해볼 수 있도록 글 남겨주셔서 감사해요! 궁금증 해결에 도움이 되었으면 좋겠습니다!👍🏻
