### ISSUE TITLE
[MEJ-003] WeakHashMap에 관한 질문

### ISSUE THREAD

**Issue by ssh2957** [Glenn-syj/more-effective-java#70]
Based on: #57 by @undeadtimo
가비지 컬렉터가 잡아내지 못하는 객체들을 처리하여 메모리를 잘 관리 하는 방법에 관한 글 잘 읽었습니다.
저또한 이번에 close()를 하지 않는다면 가비지 컬렉터가 잡아내지 못하여 메모리를 잘 관리 하지 못한다는
주제로 글을 썼기에 더 관심있게 읽을 것 같습니다. 그중 책에서는 캐쉬와 리스너와 관련된 문제를 해결할수 있는 
WeakHashMap의 예시가 없어 이해하기 어려웠는데 undeadtimo님의 예시와 코드와 설명 덕분에 어떻게 쓰이는지는 이해를 할 수 있었습니다.
여기서 질문이 생겼는데요 1. WeakHashMap 의 약한 참조가 값만 복사해오는 얕은 복사와 같은 뜻인지 궁금합니다.
 2. HashMap과 WeakHashMap 차이점이 글에서 쓰인 key로 사용되는 부분이 null 처리될 경우, key와 묶인 value가 더 이상 사용되지 않는 객체일 때, 가비지 컬렉터로 하여금 처리하도록 만든다. 
이외에 다른것도 있는지 궁금합니다.

**Comment by undeadtimo** [comment]
ssh2957님의 좋은 질문 감사합니다.

우선 '약한 참조'와 '얕은 복사'는 다른 개념임을 알려드립니다.

`약한 참조` 란 참조 방식 중에서 특정 객체에 대하여 WeakReference 객체만이 참조를 하고 있다면, 해당 객체를 Garbage Collector로 하여금 제거하도록 만드는 방식을 말합니다.

`얕은 복사` 란 복사하고자 하는 대상의 참조를 복사하는 것을 일컫는 것으로, 원본의 값이 변경되면 복사하여 생성한 데이터 또한 변경되는 형태를 보입니다.

이 `얕은 복사`는 대상의 데이터만을 복사하여 원본 데이터가 변경되어도 복사 데이터는 변경되지 않는 `깊은 복사`와 대조적인 개념입니다.

Reference:
https://developer.mozilla.org/ko/docs/Glossary/Shallow_copy
https://www.baeldung.com/java-reference-types

---

HashMap과 WeakHashMap의 차이는 ssh2957님이 말씀해주신 것과 비슷합니다. 

정확히는 key로 사용되는 부분에 대한 참조가 WeakReference 객체만 존재하거나 key를 참조하는 객체가 없다면 Garbage Collector로 하여금 처리하도록 만드는 것입니다.

HashMap과 WeakHashMap의 차이점에 대해서는 이 부분 외의 다른 점은 찾아보았으나 발견하지 못하였습니다.
이 둘의 차이점은 key에 대한 참조에 따른 처리 방법만이 존재하는 것 같지만, 추후에도 차이점을 탐색하여 발견하게 된다면 정보를 공유하도록 하겠습니다.

**Comment by ssh2957** [comment]
약한 참조'와 '얕은 복사'의 개념을 확실히 이해 할 수 있었습니다! 감사합니다.
