### ISSUE TITLE
서비스 제공자 프레임워크 + JDBC 관련 흥미로운 블로그 글 공유합니다.

### ISSUE THREAD

**Issue by clare-u** [Glenn-syj/more-effective-java#8]
[https://sihyung92.oopy.io/java/service-provider-framework](https://sihyung92.oopy.io/java/service-provider-framework)

앞부분 내용 중
→ *정적 팩토리 메서드를 활용하면, 반환할 객체의 클래스가 컴파일 타임에는 존재하지 않아도 된다. 특정한 하위 타입이 필요한 런타임 시점 때, 정적 팩토리 메서드 내에서 찾을 수만 있으면 된다.*
라는 요약도 좋았고, 

*Line 2. 서비스 제공자 프레임워크를 만드는 근간이 된다.* 파트에서 서비스 제공자 프레임워크에 대한 이해를 돕도록 JDBC를 예시로 들어 서술한 부분이 재미있었네요. 오늘 배웠던 JDBC에 대해서도 다시 복습할 수 있어 좋았습니다.

아래 레퍼런스에 있는 백기선님 유투브 영상 [‘자바, 서비스 제공자 프레임워크’](https://www.youtube.com/watch?v=R-YvrkKkOAM) 도 10분 분량인데 재밌었습니다. 다들 한 번 보시면 기억에 잘 보관될 것 같네요!

**Comment by Glenn-syj** [comment]
좋은 글 공유해주셔서 감사합니다!

추가로, 올려주신 사이트 내에서의 요약 파트에서, 이해는 좋지만 코드는 조금 핀트가 엇나가 있는 것 같으니 제가 쓴 글의 레퍼런스를 참고해주세요!
