### ISSUE TITLE
[MEJ-004] 애그리게이션과 연관에 대한 질문

### ISSUE THREAD

**Issue by clare-u** [Glenn-syj/more-effective-java#83]
Based on: [chapter_04/item18_손영준_객체-사이-네-가지-관계.md](https://github.com/Glenn-syj/more-effective-java/blob/glenn-syj/chapter_04/item18_%EC%86%90%EC%98%81%EC%A4%80_%EA%B0%9D%EC%B2%B4-%EC%82%AC%EC%9D%B4-%EB%84%A4-%EA%B0%80%EC%A7%80-%EA%B4%80%EA%B3%84.md)  by @Glenn-syj 

---

상속과 컴포지션, 애그리게이션, 연관에 대한 글 잘 보았습니다. 상속에 대해서는 몇 번 학습한 적이 있어 잘 읽혔는데요, 나머지 세 부분에 대해 추가적인 학습을 해 보니 상속과 컴포지션에 대해서는 아래와 같이 이해할 수 있었습니다.

> **상속**
> 상속은 extend를 활용하여 한 클래스를 다른 클래스에서 파생시킨다.
> ex) animal이라는 클래스를 extend 받아 확장한 사람이라는 클래스가 파생된다.
> ```java
> public class human extends animal{
> 	//... do something
> }
> ```
> 
> **컴포지션**
> 컴포지션은 parts, 즉 클래스를 구성하는 부분의 합으로 정의한다
> ex) 클래스 필드 내에 private or public 필드로 클래스의 인스턴스를 참조하게 하고
> 해당 클래스를 구성하는 부분의 합으로 정의된다.
> 클래스의 구성요소로 쓰인다는 뜻에서 composition이라고 한다.
> ```java
> public class House {
> 	private Bedroom bedroom;
>     private LivingRoom livingRoom;
>     //.. do something
> }
> ```
> 컴포지션의 경우 컴포지션을 통해 생성된 클래스와 객체는 느슨하게 결합되어(loosely coupled) 코드를 손상시키지 않고 구성 요소들을 바꿀 수 있다.

다만 애그리게이션과 연관에 대해서는 이해가 어려워서, 혹시 추가로 예시 코드를 작성해 주실 수 있으실까요?

참고한 자료
https://velog.io/@vino661/%EC%83%81%EC%86%8D%EA%B3%BC-%EC%BB%B4%ED%8F%AC%EC%A7%80%EC%85%98%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C

**Comment by Glenn-syj** [comment]
사실 aggregation 과 association 사이에서, 코드 상의 차이점은 없는 것으로 보입니다. 만약 코드 상에 차이점이 존재한다면, 그것은 설계 단계에서의 차이가 나타난 것으로 볼 수 있습니다. 즉, 두 종류가 갖는 차이는 오직 논리적인 차이일 뿐입니다.

```java
// aggregation example
class Wheel {
    Car car;
}

class Car {
    List<Wheel> wheels;
}
```

```java
// association example
class Child {
    Mother mother;
}

class Mother {
    List<Child> children;
}
```

위 두 코드에서, 실제로 차이는 논리적인 구조에서 (1) 차는 바퀴를 소유하나, (2) 어머니는 자식을 소유하지 않음으로 구분될 뿐입니다. 따라서 UML(Unified Modeling Language)에서도 다르게 표현되나, 코드 상에서의 차이는 없다고 생각합니다.

**Comment by clare-u** [comment]
레퍼런스를 제대로 참고하지 못했었네요! 예시 코드를 읽어보니 정말 코드상으론 차이가 없는게 신기하네요. 설명까지 붙여주시니 이해가 잘 되었습니다 감사합니다!
