### ISSUE TITLE
[MEJ-004] private 중첩클래스에 대한 이해

### ISSUE THREAD

**Issue by yngbao97** [Glenn-syj/more-effective-java#84]
Based on: #79 by @ssh2957 

item16을 읽으면서 private 중첩클래스에 대한 언급이 궁금했는데, 마지막에 들어주신 코드 예시와 설명 덕분에 해당 방식의 이점을 깨달았습니다.

>내부 클래스의 경우 내부 클래스에 private 제어자를 적용해줌으로써, 캡슐화를 통해 클래스를 내부로 숨길 수있다.

첨부해주신 예시 코드를 직접 실행해보면서 다음 내용을 더 확실히 이해했습니다.
1. 내부 클래스(private)가 속한 외부 클래스만 해당 내부 클래스에 접근할 수 있다.
2. 내부 클래스에서는 자신이 속한 외부 클래스의 멤버들에 접근할 수 있다.
3. 내부 클래스 구조를 외부에 공개하지 않을 수 있다.

접근자 메서드를 대체하는 기능 뿐만 아니라, 보다 구조적인 프로그래밍이 가능하겠다는 걸 맛보기로나마 느낄 수 있었네요!
좋은 예시와 설명 감사합니다!

**Comment by ssh2957** [comment]
제가 기초가 부족하다 보니 제가 이해 할 수 있는코드로 예제코드를 찾아 실험하고 있습니다. 제 예제 코드가 이해하시는데 도움이 되었다니 감사합니다!!
