### ISSUE TITLE
[MEJ-004] compareTo()와 hashCode()의 비교 및 보충설명

### ISSUE THREAD

**Issue by FickleBoBo** [Glenn-syj/more-effective-java#85]
Based on: #78 by @yngbao97 

객체에 순서를 부여하고자 할 때 사용했던 `compareTo()`에 대해 `equals()`와 `hashCode()`와 연결 지어 설명해 주셔서 고민할 점이 있었던 탐구 주제였던 것 같습니다. 이전 아이템에서 HashTable을 예시로 탐구를 했었는데, HashSet도 비슷하지 않을까 싶었는데 내부 구조가 많이 다를 수도 있을 것 같다는 생각이 들었습니다. 

예시 코드와 설명에서 HashSet은 `equals()`로, TreeSet은 `compareTo()`로 자료를 비교하여 저장한다는 개념에서 논리를 전개한 것으로 이해했습니다. 

2번의 경우 처음엔 두 객체의 판단 기준이 되는(equals) id가 달라서 HashSet에는 2개가, 두 객체의 판단 기준이 되는(compareTo) score는 같아서 Treeset에는 1개의 객체가 저장될 것으로 예상했습니다. `compareTo()`를 id에 대해서도 판단하도록 수정했을 경우, 두 객체의 score는 같지만 id는 다르므로 이번에는 TreeSet에도 2개의 객체가 저장될 것으로 예상했습니다. (HashSet은 무관하게 2개)

추가 테스트의 경우 HashSet은 `Student(1, "육예진", 50)`와 `Student(2, "육민우", 50)` 2개가 저장되지 않을까 했는데, `Student(2, "송창용", 50)`까지 저장되는 것에 부끄러움을 느꼈습니다. 본문의 내용대로 `hashCode()`를 재정의 하지 않아 발생한 것으로 생각하는데, 이는 hash를 사용하는 자료구조에서는 동일한 객체인지를 판단할 때, `hashCode()`를 통해 같은 해시값이 나왔는지를 판단하고 같은 해시값이 나오면 `equals()`로 한 번 더 판단하는 구조이기 때문으로 생각합니다.(오피셜한 사진은 아니지만 "자바 equals hashtable"로 검색하면 나오는 이미지에서 확인할 수 있습니다.) new로 생성한 객체는 보통 다른 해시값을 가지므로(비둘기 집의 원리에 의해 우연찮게 같을 수도 있음) 사실 `equals()`만 재정의 한 것은 HashTable이나 HashSet에서 사용하는데 아무 의미가 없을 것으로 생각됩니다.(`hashCode()`로 판단하는 선에서 다른 객체로 판단함) 이것이 `equals()`를 재정의 하였을 때 `hashCode()`를 재정의 해야 하는 이유라고 생각하며, 이는 대부분의 경우 `equals()` 재정의 이후 hash를 사용하는 자료구조를 사용하기 위함으로 생각합니다.(개발자의 의도와 동일한 결과를 보장하기 위함) 

`hashCode()`는 동일하다고 판단되는 객체에 대한 정수를 반환하고, 이는 인덱싱에 활용 가능한 정보가 될 수 있으므로 `equals()`가 있는데 `hashCode()`가 존재하는 이유가 뭘까에 대한 답도 되지 않을까 싶습니다. 추가로 참고 자료에서 'Set이 HashTable을 사용하는 자료형이다'라는 문장은 자바 공식 문서와 컬렉션 상속 구조 이미지를 통해 동의하기 어렵다는 생각을 했습니다. (HashSet은 Set 인터페이스를 상속받고 HashMap과 HashTable은 Map 인터페이스를 상속받고 있는 것으로 확인했습니다. 이름에 Hash가 들어가는 클래스는 내부적으로 `hashCode()`를 사용해서 용어의 혼용 때문에 생긴 실수라는 생각이 들었으며 해당 클래스들이 동일한 원리로 `hashCode()`를 사용하는지까지는 찾지 못했습니다.) 또한, 저번 review와 마찬가지로 Object 클래스의 `hashCode()`가 메모리 주소값을 정수로 변환했는지 여부는 물론 메모리 주소값을 해싱 알고리즘에 일부 활용하는지 여부도 확인하기 어려웠습니다.(review 참고자료처럼 스택오버플로우에서도 의견이 분분한 것으로 확인했었습니다.) 

TreeSet은 처음 보는 자료구조였는데, 같은 Set 인터페이스를 상속받고 있지만 구조부터 활용까지 완전히 다른 목적으로 활용될 것으로 보여 흥미로웠으며, 추가 테스트의 결과와 참고 자료를 통해 자료의 값이 같은지에(자료의 동등성은 이와 다른 개념으로 보여) 신경 쓰며 정렬하려 O(logN)의 시간복잡도로 자료를 다루는데 의의가 있을 것으로 보였습니다.

**Comment by yngbao97** [comment]
>hashCode()를 통해 같은 해시값이 나왔는지를 판단하고 같은 해시값이 나오면 equals()로 한 번 더 판단하는 구조이기 때문

먼저, 원소의 동치성을 판단할때 equals와 hashCode 사용 순서를 반대로 생각하고 있었는데 답변주신 내용을 통해 바로잡을 수 잇었습니다. 

>참고 자료에서 'Set이 HashTable을 사용하는 자료형이다'라는 문장은 자바 공식 문서와 컬렉션 상속 구조 이미지를 통해 동의하기 어렵다는 생각을 했습니다

또, 레퍼런스로 첨부했던 블로그 글에 오개념이 존재한다는 점도 발견하지 못했는데, 덕분에 HashTable과 HashCode에 대해 다시한번 찾아보고 공부해볼 수 있었습니다. 

일부 오개념을 가지고 작성되었던 글에 보충설명 달아주셔서 감사합니다. 
앞으로 보다 공식적인 내용을 참고하여 글 작성하도록 하겠습니다!
