### ISSUE TITLE
[MEJ-004] 불변 클래스 String에 대한 재인식

### ISSUE THREAD

**Issue by yngbao97** [Glenn-syj/more-effective-java#86]
Based on: #81 by @undeadtimo 

지난번 제가 작성했던 equals 메서드 관련 글(#55 )에 남겨주셨던 이슈 (#67 )에서 String 클래스 상속 시도에 대해 말씀해주셨었는데, 이 부분을 불변클래스의 특성과 이점에 연결지어 탐구해주신 점이 인상깊고 불변 클래스에 대한 이해에 보다 도움이 되었습니다.

책을 읽으면서 String이 불변 클래스라는 문장을 봤는데도 크게 신경쓰지 않았었는데, 정리해주신 글을 읽으면서 불변클래스였기 때문에 나타났던 특징과 이점들이 잘 이해되었습니다.

이전에 문자열 관련 알고리즘 문제를 풀면서 String 객체에 문자를 무수히 반복적으로 추가하려고 시도했다가 실행까지 시간이 매우 오래 걸렸던 기억이 있습니다. 당시에는 코드를 이렇게 작성하면 시간이 오래걸린다는 말만 듣고 그렇구나 넘겼었는데 불변클래스 글을 읽고 아차 싶어서 아주 간단하게 테스트 해봤어요.

```java
String b = "헬로";
System.out.println(b.hashCode());		// 1744880

b = "안녕";
System.out.println(b.hashCode());		// 1611021

b += "하세요";
System.out.println(b.hashCode());		// 803356551
```
값을 변경하는 것도, 문자를 추가하는 것도 기존 객체의 값이 변경되는 것이 아니라 새로운 객체가 생성되고 그 참조값이 새롭게 할당되고 있었음을 깨달았습니다. 
덕분에 그동안 대강 넘어갔던 부분에 대해 확실히 인지할 수 있었고, 불변객체화를 통해 얻을 수 있는 이점도 생각해볼 수 있었습니다.

추후 새로운 클래스를 정의하게 된다면 해당 클래스의 특성과 목적에 따라 변경 가능성 필요여부에 대해 고민해보고, 불변클래스화를 시도해볼 수 있겠네요!
좋은 탐구 감사합니다!

**Comment by undeadtimo** [comment]
좋은 보충설명 감사합니다 yngbao97님.

불변 객체의 특징 중, 함수형 프로그래밍에 대한 예시를 작성해주셨군요. 단지 특성 중 하나로만 알고 있었으나, 이렇게 실제 경험담과 함께 코드를 제시해주니 불변객체에 대해 더 잘 이해하게 되었습니다.

불변 클래스인 String은 내부 값을 변화시켜도 해당 객체가 변화되는 것이 아닌,  값만을 가져와 연산을 처리하고 결과값을 갖는 새로운 객체를 반환하는 것을 경험하셨군요.

equals 메서드에 관한 글에서부터 이어져온 의문점이 새로운 지식으로 yngbao97님께 반환되어 신기하기도 하고 뿌듯하기도 하네요. 감사합니다.
