### ISSUE TITLE
[MEJ-004] 가비지 컬랙터와 데몬 스레드에 관해서

### ISSUE THREAD

**Issue by undeadtimo** [Glenn-syj/more-effective-java#87]
Based on: #80 by @clare-u 

clare-u님의 글 잘 읽었습니다.

스레드의 개념에 대해서는 어렴풋이 알고 있었지만, 프로세스와 멀티 프로세스와의 관련성에 대해서는 자세히 알고 있지 않았기에, clare-u님의 글을 읽고 스레드와 프로세스에 대한 개념을 이해할 수 있게 되었습니다.

프로세스란 하나의 '프로그램'이며, 스레드느 해당 프로그램 내에서 이루어지는 하나의 '작업 단위'라는 키워드를 알게되어 이해하기 더 수월하였습니다.

clare-u 님께서 어려웠던 점으로 꼽아주신 데몬 스레드와 가비지 컬렉터에 대해서 저 또한 탐색해보았습니다.

stackoverflow에서도 가비지 콜랙터가 daemon thread라는 의견이 있었고, 다른 사이트에서도 가비지 콜랙터가 daemon thread라 설명하고 있었습니다.

따라서 clare-u 님께서 찾아보신 oracle 문서에서는 가비지 콜랙터의 여러 구현 방식과 작동 원리에 초점을 맞추고 있기에 daemon thread에 대한 언급이 없었던 것이라 추측이 됩니다.

다만, oracle 문서에서 가비지 컬랙터에 대해 설명할 때 daemon thread에 대해서는 직접적으로 언급하지 않지만 daemon thread의 특징을 같이 설명하고 있습니다.

`Instead, the omniscient GC housekeeper process works behind the scenes quietly discarding objects that are no longer useful and tidying up what’s left.`

이 구문에서 daemon thread의 자동적인 동작과 메인 user thread를 방해하지 않는다는 특징이 `behind the scenes quietly discarding objects` 라는 표현으로 나타나고 있는 것 같습니다.

혹시 제가 생각하는 것이 옳지 않다면 말씀해주시기 바랍니다.

Reference:

https://www.baeldung.com/java-daemon-thread

https://stackoverflow.com/questions/5218848/is-garbage-collector-a-daemon-thread

https://www.geeksforgeeks.org/daemon-thread-java/?source=post_page-----3b89ce606b04--------------------------------

**Comment by clare-u** [comment]
레퍼런스들에서 탐구를 위한 노력의 흔적이 엿보여 감동적이네요!! 말씀해 주신 대로 직접적인 언급 대신 특징으로 데몬 스레드임을 나타내 준 듯 하네요. 추가 조사를 하려 했지만 언어의 벽을 느끼고 있었는데 이렇게 제 의문을 해소시켜 주셔서 감사합니다.

**Comment by undeadtimo** [comment]
저 또한 덕분에 가비지 컬렉터와 daemon thread에 대해 탐색하면서 평소에 관심을 가졌던 가비지 컬렉터에 대해 의문을 해소할 수 있게 되었습니다. 감사합니다!
