### ISSUE TITLE
[MEJ-004] 불변 객체 및 상수와 String pool에 대한 질문

### ISSUE THREAD

**Issue by FickleBoBo** [Glenn-syj/more-effective-java#88]
Based on : #81 by @undeadtimo

String이 불변 클래스라는 점이 학습을 하며 굳이라는 생각이 들 때가 있었습니다. 알고리즘 학습을 하며 StringBuilder 클래스를 자주 사용하게 되니 String이 불편한 점이 많다라고 생각했는데 이번 탐구를 통해 개발자의 의도를 엿볼 수 있어 좋은 글이었던 것 같습니다. 

@undeadtimo님의 1번 Memory 부분에 대한 탐구와 관련에 이해하는 과정에서 약간의 어려움과 궁금증이 있었습니다. 
### 1. String이 불변 클래스로 설계되었기 때문에, JVM은 일정량의 메모리 공간을 String pool에 할당하고, 각각의 String 값들은 String pool을 참조할 수 있다. 
불변 클래스는 내부 값을 변경할 수 없는 클래스로 이해했는데, 이것이 JVM에 메모리 공간 할당까지 이어지는 것과 어떤 관계가 있을까 싶었습니다. 관련 자료들을 찾아보며 String pool 외에 contant pool 혹은 runtime contant pool 등의 개념을 메모리와 연결지어 설명하는 글들이 있었는데, 지금 수준에서 이해하기 많이 어렵기도 하고 자료마다 개념도 약간씩 다른 것 같기도 하고 공식적인 자료들을 찾기도 어려웠는데, 공통적으로 String pool에 대한 언급이 있었던 점과 상수에 대해 연결지어 설명되었던 점을 토대로 자바에서 상수(==불변 객체?)는 새로운 객체를 생성하는 것보다 기존의 객체를 다시 참조하는 것이 효율적이어서 constant pool이 등장했고 String의 경우 가장 자주 사용하는 객체인만큼 상수로 만들고 전용 공간(String pool)을 주는 것이 프로그래밍에 효율적이어서라는 생각이 들었습니다. 
이에 @undeadtimo님은 String의 Memory적 측면에 대해 어떻게 생각하시는지 궁금합니다.

**Comment by undeadtimo** [comment]
FickleBoBo님의 질문 감사드립니다.

내부 값이 변경되지 않는 '불변 클래스'와 JVM 내부에 String Pool이라는 메모리 공간을 할당하는 것의 관계에 대하여 제가 이해한 바를 설명드리도록 하겠습니다.

```java
String str1 = "helllo";
String str2 = "hello";
```

str1 변수가 생성되면서, JVM 메모리 공간에 String Pool 영역이 형성되고 그곳에 hello 문자열에 해당하는 주소가 지정됩니다.
이후,
str2 변수가 리더럴 문자열로 초기화되면서 생성될 때, str2는 String Pool 공간에 hello 문자열에 해당하는 주소가 존재하므로, 같은 곳을 참조하게 되면서, 원래라면 두 공간을 차지할 메모리가 하나로 줄어들게 되었습니다.

만약 String 클래스가 불변 클래스가 아니라고 가정하고, 불변 클래스가 아닌 String 클래스가 String Pool 을 같은 원리로 사용하면 어떻게 될까요.

```java
String str1 = "hello";
String str2 = "hello";
```

메모리를 절약하기 위해 이 둘은 String Pool 내부의 같은 공간을 참조하게 됩니다.
그러나, 
```java
str1 = "bye";
```
이처럼 str1 변수에 다른 문자열 값을 할당해준다면, str1과 str2 변수 모두 "bye" 문자열로 값이 바뀌게 될 것입니다.

심지어 str2는 의도적으로 같은 주소를 참조하게 한 것이 아닌데도 str1 변수가 바뀌면서 str2 또한 데이터가 변경되는 일이 발생합니다. 

또한 이 때,
```java
String str3 = "hello";
```
hello 문자열 값을 갖는 또 다른 String 데이터 타입인 str3이 생성된다고 가정하면,
이 str3는 str1, str2 변수가 참조하는 주소값을 같이 공유하지 못하고 또 다른 메모리 공간을 참조하게 되어 메모리 절약에 실패하게 됩니다.

만약 String 클래스가 불변 클래스 속성을 가진 채로
```java
str1 = "bye";
```
코드가 실행되었다면, str1은 불변 객체이기 때문에 값이 바뀌는 것이 아닌, "bye" 데이터를 갖는 또 다른 String 객체가 되는 것입니다.

해당 메모리 주소의 값은 그대로 "hello"이기에 str2 변수의 문자열 값이 의도치않게 변경되는 일도 없을 것이고,

```java
String str3 = "hello";
```

처럼 추가로 "hello" 문자열을 갖는 String 데이터가 생성되어도 기존의 "hello" 문자열에 대응하는 String Pool 공간을 가리키게 되어 메모리를 절약할 수 있게 됩니다.

혹여나 저의 부연설명이 이해되지 않거나 와닿지 않는다면, 말씀해주시기 바랍니다.

추가로, FickleBoBo 님이 말씀해주신 constant pool 과 runtime constant pool 은 저에게도 탐구해보지 못한 영역이기에 후에 탐구하여 String pool과의 연관성에 대해 정리 후 공유해보도록 하겠습니다.

**Comment by FickleBoBo** [comment]
좋은 답변 감사합니다. 저도 @undeadtimo님의 테스트 코드를 토대로 몇가지 테스트들을 해보며 String은 사용감이 기본 타입 같은 특이한 클래스라는 생각이 들었습니다. 
공식 자료에서는 찾지 못해서 잘못된 정보일 수 있지만 String은 내부적으로 char배열이 사용된 것으로 말하는 게시글들이 있었습니다. String이 배열을 기반으로 만들어졌다면 이를 데이터를 수정할 수 있게 구현했을 경우, 직관적이지 않은 여러 에러사항이 있을 것으로 예상됩니다!!
