### ISSUE TITLE
[MEJ-001] 빌더 패턴의 단점에 대한 보충 설명

### ISSUE THREAD

**Issue by Glenn-syj** [Glenn-syj/more-effective-java#9]
Based on: #3 by clare-u 

### 들어가며

빌더 패턴의 장점과 단점에 대한 블로흐의 서술은 아래 정도로 요약해볼 수 있겠습니다.

**장점**
1. 스레드 안전성 (thread safety) 확보
2. 객체의 일관성 유지
3. 코드 가독성 확보

**단점**
1. 성능 (빌더 생성 이후 객체 생성 필요)
2. 가성비 (매개 변수 4개 이상부터 시작하라는 찝찝한 서술)

그런데 제가 보기에는 가장 중요한 단점이 빠져있습니다. 이러한 단점은 바로 빌더 패턴을 과용(overuse)하거나 잘못 사용할 때 드러나는데요. 읽어보니 좋으면서도 동의 가는 글이 있어 추가적으로 설명 드립니다. (이는 곧 Effective Java를 맹목적으로 받들지 말라는 뜻이기도 합니다.)

### 빌더 패턴의 진정한 단점

빌더 패턴은 여전히 _컴파일 시점_에서 모든 필드값이 설정되어 있는지 확인할 수 없습니다. 이는 JavaBeans 패턴과 함께 공유하는 문제이기도 합니다.

```Java
// based on the sample code for explaining from below
// https://dev.to/siy/when-builder-is-anti-pattern-3j92
  final MyPojo pojo = MyPojo.newBuilder()
                            .setThis(...)
//                          .setThese(...)
                            .setThat(...)
                            .setSomethingElse(...)
                            ...
                            .build();
```

위 코드에서 사실 `setThese()`라는, `MyPojo.these`에 대한 메소드를 실수로 빼먹었다면 어떨까요? 그래도 `build()`는 문제없이 진행될 겁니다. 물론 `build()`에 자체적으로 null이나 기본값을 검증하는 로직을 추가한다면 해결될 지도 모릅니다.

하지만 검증 로직의 추가는 완벽한 해결책이 될 수 없습니다. 기존에 NPE(Null Point Error)를 _컴파일 시점_에 일으키던 코드가 _런타임 시점_에 검증될 뿐이라서요. 좋지 않습니다. 여러분이 코드를 작성했을 때를 떠올려봅시다. _컴파일 시점_에 오류 위치와 에러/예외 종류까지 받아서 수정하는 게 나았는지, _런타임 시점_에 잘못된 부분을 찾으려고 전전긍긍했던 시간이 나았는지요.

이 글 저자는 다음과 같이 말합니다.

> The build() method must produce complete instance. All necessary fields must be set to reasonable defaults if user did not provide values for them.

즉, `build()` 메소드는 값이 전달되지 않아 필드가 설정되지 않았을 때, 적절한 기본값으로 설정되어야 합니다. 저자는 대안적인 방식으로 이전에 배운 '정적 팩토리 메소드'를 소개하기도 하네요! 

추가적으로 더 작지만 어쩌면 더 중요한 단점을 고려해볼 수 있겠습니다. 지나치게 많은 필드를 가지고 있는 객체는 이미 그 설계 상에서 좋지 않은 코드를 가지고 있을지도 모른다는 점입니다. 이 글의 저자가 제시한 개선은 아래에 간단하게 남겨두겠습니다!

> - group linked fields into more complex objects (like extract all user details into user object + contact info object)
> - use projections - narrower POJO's for specific use cases
> - kinda inverse version of projections - create core POJO which contains most often used fields and several specific POJO's for various use cases (and use core POJO as single field) The goal of all these approaches is the same - reduce number of fields. This simplifies use of such a big POJO and in the same time reduces risk of error.

### References

https://dev.to/siy/when-builder-is-anti-pattern-3j92

**Comment by clare-u** [comment]
오 좋은 글이네요! 저도 읽으면서 빌더 패턴도 상대적인 장단점을 넘어서서 엄청 좋아보이진 않는데 싶었는데 잘 서술되어 있는 거 같습니다.

> 여러분이 코드를 작성했을 때를 떠올려봅시다. _컴파일 시점_에 오류 위치와 에러/예외 종류까지 받아서 수정하는 게 나았는지, _런타임 시점_에 잘못된 부분을 찾으려고 전전긍긍했던 시간이 나았는지요.
부분이 참 공감가네요 ㅎㅎ

**Comment by Glenn-syj** [comment]
그래도 여전히 장점은 있어 보입니다! 사실 빌더 패턴만의 장점이 또 없을까에 대해 고민을 조금 해봤는데요. 오히려 null값을 허용하고 또 이용하는 경우, 혹은 단순한 setter 방식을 넘어서는 맥락에서는 확실히 이해에 좋게도 느껴집니다. (그래서 위 글에서도, 일반적인 POJO에서 빌더 패턴을 과하게 이용하는 것을 경계하는 듯 보이네요!)

아래는 제가 안드로이드를 공부하며 썼던, OkHttp라는 HTTP 통신 라이브러리 코드입니다. 물론 직접적으로 빌더 패턴을 사용한다고 서술되어 있습니다. (코틀린 코드이긴 합니다!)
> Using OkHttp is easy. Its request/response API is designed with fluent builders and immutability. It supports both synchronous blocking calls and async calls with callbacks.

1. GET Requst
```kotlin
// This program downloads a URL and prints its contents as a string.
// https://square.github.io/okhttp/
OkHttpClient client = new OkHttpClient();

String run(String url) throws IOException {
  Request request = new Request.Builder()
      .url(url)
      .build();

  try (Response response = client.newCall(request).execute()) {
    return response.body().string();
  }
}
```

2. POST Request
```kotlin
// This program posts data to a service. 
// https://square.github.io/okhttp/
public static final MediaType JSON = MediaType.get("application/json");

OkHttpClient client = new OkHttpClient();

String post(String url, String json) throws IOException {
  RequestBody body = RequestBody.create(json, JSON);
  Request request = new Request.Builder()
      .url(url)
      .post(body)
      .build();
  try (Response response = client.newCall(request).execute()) {
    return response.body().string();
  }
}
```

GET 방식에서는 body를 이용하지 않기에, `post(body)` 역시 이용되지 않는데요. `post(body)`라는 명명이 굉장히 직관적으로 다가오기도 합니다. 이러한 맥락에서는 빌더 패턴이 더 명확한 의미를 전달하는 것으로 보입니다.

**Comment by clare-u** [comment]
> 그래도 여전히 장점은 있어 보입니다! 사실 빌더 패턴만의 장점이 또 없을까에 대해 고민을 조금 해봤는데요. 오히려 null값을 허용하고 또 이용하는 경우, 혹은 단순한 setter 방식을 넘어서는 맥락에서는 확실히 이해에 좋게도 느껴집니다. (그래서 위 글에서도, 일반적인 POJO에서 빌더 패턴을 과하게 이용하는 것을 경계하는 듯 보이네요!)


POJO가 어떤 의미인지 검색해 보니 Plain Old Java Object 라고 나오고 특징들도 서술되어 있네요! 좋은 용어 하나 배워갑니다.
