### ISSUE TITLE
[MEJ-004] 다양한 예시를 통한 새로운 개념 이해

### ISSUE THREAD

**Issue by ssh2957** [Glenn-syj/more-effective-java#93]
based on: #78 by @yngbao97
평소 정렬을 할때 기준으로 해야하는 인자가 많을때 사용해야 하는 comepareTo 메소드가 class에 익숙하지 않았을 때
접했어서 보다 간단하게 comepareTo를 사용할 수 있는 람다 방식을 외어서 그동안 사용하고 있었습니다.
상속과 오버라이드에 대한 지식이 쌓인 지금 예진 님의 comepareTo 예시 코드를 보며 comepareTo가 어떻게 작동되는지
정확히 이해할 수 있어 앞으로는 암기한 람다 식이 아닌 제가 class에서 메소드를 바로 입력할 수 있는 용기가 생겼습니다.
또한 HashSet과 TreeSet에 대한 자료구조를 사용해 본 적 없어 어떠한 차이가 있는지 생각해 볼 시간이 없었습니다.
하지만 예진님의 글을 통한 설명으로 HashSet과 TreeSet에 대한 이해도를 높이고바로 헷갈릴 만한 점을, 코드를 통해 알려주시니 HashSet과 TreeSet이 어떠한 차이점이 있는지 바로 결과를 통해 알 수 있었습니다.
항상 예진 님의 글을 보면 코드를 직접 짜시고 다양한 예시를 통해 어려운 개념을 쉽게 이해하고 있습니다. 감사합니다.

**Comment by yngbao97** [comment]
책의 개념이 어렵다고 느껴져서 최대한 단순한 형태로 이해해보고자 간단한 코드로 작성해서 테스트해보기를 시도한 게 많은 도움이 되셨다니 뿌듯하고 감사하네요!

가능한 레퍼런스로 이중체크해가며 작성하도록 노력하고 있지만, 검증되지 않은 코드가 포함되어있을 수 있으니 예시 코드를 직접 옮겨서 테스트해보시길 권장드립니다!
앞으로도 도움이 되는 글을 작성할 수 있도록 노력하겠습니다 ㅎㅎ 감사해요!
